// This file is generated by kconfig_compiler_kf6 from krema.kcfg.
// All changes you do to this file will be lost.
#ifndef KREMASETTINGS_H
#define KREMASETTINGS_H

#include <QCoreApplication>
#include <QDebug>
#include <kconfigskeleton.h>
#include <qglobal.h>

class KremaSettings : public KConfigSkeleton
{
    Q_OBJECT
public:
    KremaSettings(QObject *parent = nullptr);
    ~KremaSettings() override;

    /**
      Set Icon size in pixels
    */
    void setIconSize(int v)
    {
        if (v < 12) {
            qDebug() << "setIconSize: value " << v << " is less than the minimum value of 12";
            v = 12;
        }

        if (v > 96) {
            qDebug() << "setIconSize: value " << v << " is greater than the maximum value of 96";
            v = 96;
        }

        if (v != mIconSize && !isIconSizeImmutable()) {
            mIconSize = v;
            Q_EMIT IconSizeChanged();
        }
    }

    Q_PROPERTY(int iconSize READ iconSize WRITE setIconSize NOTIFY IconSizeChanged)
    Q_PROPERTY(bool isIconSizeImmutable READ isIconSizeImmutable CONSTANT)
    Q_PROPERTY(int defaultIconSizeValue READ defaultIconSizeValue CONSTANT)
    /**
      Get Icon size in pixels
    */
    int iconSize() const
    {
        return mIconSize;
    }

    /**
      Is Icon size in pixels Immutable
    */
    bool isIconSizeImmutable() const
    {
        return isImmutable(QStringLiteral("IconSize"));
    }

    /**
      Get Icon size in pixels default value
    */
    int defaultIconSizeValue() const
    {
        return defaultIconSizeValue_helper();
    }

    /**
      Set Height/Thickness of the dock panel
    */
    void setPanelHeight(int v)
    {
        if (v < 10) {
            qDebug() << "setPanelHeight: value " << v << " is less than the minimum value of 10";
            v = 10;
        }

        if (v > 300) {
            qDebug() << "setPanelHeight: value " << v << " is greater than the maximum value of 300";
            v = 300;
        }

        if (v != mPanelHeight && !isPanelHeightImmutable()) {
            mPanelHeight = v;
            Q_EMIT PanelHeightChanged();
        }
    }

    Q_PROPERTY(int panelHeight READ panelHeight WRITE setPanelHeight NOTIFY PanelHeightChanged)
    Q_PROPERTY(bool isPanelHeightImmutable READ isPanelHeightImmutable CONSTANT)
    Q_PROPERTY(int defaultPanelHeightValue READ defaultPanelHeightValue CONSTANT)
    /**
      Get Height/Thickness of the dock panel
    */
    int panelHeight() const
    {
        return mPanelHeight;
    }

    /**
      Is Height/Thickness of the dock panel Immutable
    */
    bool isPanelHeightImmutable() const
    {
        return isImmutable(QStringLiteral("PanelHeight"));
    }

    /**
      Get Height/Thickness of the dock panel default value
    */
    int defaultPanelHeightValue() const
    {
        return defaultPanelHeightValue_helper();
    }

    /**
      Set Maximum dock length as a percentage of screen width/height
    */
    void setMaxLength(int v)
    {
        if (v < 10) {
            qDebug() << "setMaxLength: value " << v << " is less than the minimum value of 10";
            v = 10;
        }

        if (v > 100) {
            qDebug() << "setMaxLength: value " << v << " is greater than the maximum value of 100";
            v = 100;
        }

        if (v != mMaxLength && !isMaxLengthImmutable()) {
            mMaxLength = v;
            Q_EMIT MaxLengthChanged();
        }
    }

    Q_PROPERTY(int maxLength READ maxLength WRITE setMaxLength NOTIFY MaxLengthChanged)
    Q_PROPERTY(bool isMaxLengthImmutable READ isMaxLengthImmutable CONSTANT)
    Q_PROPERTY(int defaultMaxLengthValue READ defaultMaxLengthValue CONSTANT)
    /**
      Get Maximum dock length as a percentage of screen width/height
    */
    int maxLength() const
    {
        return mMaxLength;
    }

    /**
      Is Maximum dock length as a percentage of screen width/height Immutable
    */
    bool isMaxLengthImmutable() const
    {
        return isImmutable(QStringLiteral("MaxLength"));
    }

    /**
      Get Maximum dock length as a percentage of screen width/height default value
    */
    int defaultMaxLengthValue() const
    {
        return defaultMaxLengthValue_helper();
    }

    /**
      Set 0: Adaptive (Hugs icons), 1: Span (Stretches to MaxLength)
    */
    void setPanelLengthMode(int v)
    {
        if (v < 0) {
            qDebug() << "setPanelLengthMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 1) {
            qDebug() << "setPanelLengthMode: value " << v << " is greater than the maximum value of 1";
            v = 1;
        }

        if (v != mPanelLengthMode && !isPanelLengthModeImmutable()) {
            mPanelLengthMode = v;
            Q_EMIT PanelLengthModeChanged();
        }
    }

    Q_PROPERTY(int panelLengthMode READ panelLengthMode WRITE setPanelLengthMode NOTIFY PanelLengthModeChanged)
    Q_PROPERTY(bool isPanelLengthModeImmutable READ isPanelLengthModeImmutable CONSTANT)
    Q_PROPERTY(int defaultPanelLengthModeValue READ defaultPanelLengthModeValue CONSTANT)
    /**
      Get 0: Adaptive (Hugs icons), 1: Span (Stretches to MaxLength)
    */
    int panelLengthMode() const
    {
        return mPanelLengthMode;
    }

    /**
      Is 0: Adaptive (Hugs icons), 1: Span (Stretches to MaxLength) Immutable
    */
    bool isPanelLengthModeImmutable() const
    {
        return isImmutable(QStringLiteral("PanelLengthMode"));
    }

    /**
      Get 0: Adaptive (Hugs icons), 1: Span (Stretches to MaxLength) default value
    */
    int defaultPanelLengthModeValue() const
    {
        return defaultPanelLengthModeValue_helper();
    }

    /**
      Set Symmetrical margin between the Glass Pill and the dock panel edges
    */
    void setIslandMargin(int v)
    {
        if (v < 0) {
            qDebug() << "setIslandMargin: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 20) {
            qDebug() << "setIslandMargin: value " << v << " is greater than the maximum value of 20";
            v = 20;
        }

        if (v != mIslandMargin && !isIslandMarginImmutable()) {
            mIslandMargin = v;
            Q_EMIT IslandMarginChanged();
        }
    }

    Q_PROPERTY(int islandMargin READ islandMargin WRITE setIslandMargin NOTIFY IslandMarginChanged)
    Q_PROPERTY(bool isIslandMarginImmutable READ isIslandMarginImmutable CONSTANT)
    Q_PROPERTY(int defaultIslandMarginValue READ defaultIslandMarginValue CONSTANT)
    /**
      Get Symmetrical margin between the Glass Pill and the dock panel edges
    */
    int islandMargin() const
    {
        return mIslandMargin;
    }

    /**
      Is Symmetrical margin between the Glass Pill and the dock panel edges Immutable
    */
    bool isIslandMarginImmutable() const
    {
        return isImmutable(QStringLiteral("IslandMargin"));
    }

    /**
      Get Symmetrical margin between the Glass Pill and the dock panel edges default value
    */
    int defaultIslandMarginValue() const
    {
        return defaultIslandMarginValue_helper();
    }

    /**
      Set Spacing between icons
    */
    void setIconSpacing(int v)
    {
        if (v < 0) {
            qDebug() << "setIconSpacing: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 16) {
            qDebug() << "setIconSpacing: value " << v << " is greater than the maximum value of 16";
            v = 16;
        }

        if (v != mIconSpacing && !isIconSpacingImmutable()) {
            mIconSpacing = v;
            Q_EMIT IconSpacingChanged();
        }
    }

    Q_PROPERTY(int iconSpacing READ iconSpacing WRITE setIconSpacing NOTIFY IconSpacingChanged)
    Q_PROPERTY(bool isIconSpacingImmutable READ isIconSpacingImmutable CONSTANT)
    Q_PROPERTY(int defaultIconSpacingValue READ defaultIconSpacingValue CONSTANT)
    /**
      Get Spacing between icons
    */
    int iconSpacing() const
    {
        return mIconSpacing;
    }

    /**
      Is Spacing between icons Immutable
    */
    bool isIconSpacingImmutable() const
    {
        return isImmutable(QStringLiteral("IconSpacing"));
    }

    /**
      Get Spacing between icons default value
    */
    int defaultIconSpacingValue() const
    {
        return defaultIconSpacingValue_helper();
    }

    /**
      Set Maximum parabolic zoom factor
    */
    void setMaxZoomFactor(double v)
    {
        if (v < 1.0) {
            qDebug() << "setMaxZoomFactor: value " << v << " is less than the minimum value of 1.0";
            v = 1.0;
        }

        if (v > 2.0) {
            qDebug() << "setMaxZoomFactor: value " << v << " is greater than the maximum value of 2.0";
            v = 2.0;
        }

        if (v != mMaxZoomFactor && !isMaxZoomFactorImmutable()) {
            mMaxZoomFactor = v;
            Q_EMIT MaxZoomFactorChanged();
        }
    }

    Q_PROPERTY(double maxZoomFactor READ maxZoomFactor WRITE setMaxZoomFactor NOTIFY MaxZoomFactorChanged)
    Q_PROPERTY(bool isMaxZoomFactorImmutable READ isMaxZoomFactorImmutable CONSTANT)
    Q_PROPERTY(double defaultMaxZoomFactorValue READ defaultMaxZoomFactorValue CONSTANT)
    /**
      Get Maximum parabolic zoom factor
    */
    double maxZoomFactor() const
    {
        return mMaxZoomFactor;
    }

    /**
      Is Maximum parabolic zoom factor Immutable
    */
    bool isMaxZoomFactorImmutable() const
    {
        return isImmutable(QStringLiteral("MaxZoomFactor"));
    }

    /**
      Get Maximum parabolic zoom factor default value
    */
    double defaultMaxZoomFactorValue() const
    {
        return defaultMaxZoomFactorValue_helper();
    }

    /**
      Set Normalize icon sizes by removing internal padding
    */
    void setIconNormalization(bool v)
    {
        if (v != mIconNormalization && !isIconNormalizationImmutable()) {
            mIconNormalization = v;
            Q_EMIT IconNormalizationChanged();
        }
    }

    Q_PROPERTY(bool iconNormalization READ iconNormalization WRITE setIconNormalization NOTIFY IconNormalizationChanged)
    Q_PROPERTY(bool isIconNormalizationImmutable READ isIconNormalizationImmutable CONSTANT)
    Q_PROPERTY(bool defaultIconNormalizationValue READ defaultIconNormalizationValue CONSTANT)
    /**
      Get Normalize icon sizes by removing internal padding
    */
    bool iconNormalization() const
    {
        return mIconNormalization;
    }

    /**
      Is Normalize icon sizes by removing internal padding Immutable
    */
    bool isIconNormalizationImmutable() const
    {
        return isImmutable(QStringLiteral("IconNormalization"));
    }

    /**
      Get Normalize icon sizes by removing internal padding default value
    */
    bool defaultIconNormalizationValue() const
    {
        return defaultIconNormalizationValue_helper();
    }

    /**
      Set Icon scale within the allocated cell (1.0 = fill, smaller = more padding)
    */
    void setIndicatorOffset(double v)
    {
        if (v < 0.5) {
            qDebug() << "setIndicatorOffset: value " << v << " is less than the minimum value of 0.5";
            v = 0.5;
        }

        if (v > 1.0) {
            qDebug() << "setIndicatorOffset: value " << v << " is greater than the maximum value of 1.0";
            v = 1.0;
        }

        if (v != mIndicatorOffset && !isIndicatorOffsetImmutable()) {
            mIndicatorOffset = v;
            Q_EMIT IndicatorOffsetChanged();
        }
    }

    Q_PROPERTY(double indicatorOffset READ indicatorOffset WRITE setIndicatorOffset NOTIFY IndicatorOffsetChanged)
    Q_PROPERTY(bool isIndicatorOffsetImmutable READ isIndicatorOffsetImmutable CONSTANT)
    Q_PROPERTY(double defaultIndicatorOffsetValue READ defaultIndicatorOffsetValue CONSTANT)
    /**
      Get Icon scale within the allocated cell (1.0 = fill, smaller = more padding)
    */
    double indicatorOffset() const
    {
        return mIndicatorOffset;
    }

    /**
      Is Icon scale within the allocated cell (1.0 = fill, smaller = more padding) Immutable
    */
    bool isIndicatorOffsetImmutable() const
    {
        return isImmutable(QStringLiteral("IndicatorOffset"));
    }

    /**
      Get Icon scale within the allocated cell (1.0 = fill, smaller = more padding) default value
    */
    double defaultIndicatorOffsetValue() const
    {
        return defaultIndicatorOffsetValue_helper();
    }

    /**
      Set Size of the status indicator dots/dashes
    */
    void setIndicatorSize(int v)
    {
        if (v < 2) {
            qDebug() << "setIndicatorSize: value " << v << " is less than the minimum value of 2";
            v = 2;
        }

        if (v > 12) {
            qDebug() << "setIndicatorSize: value " << v << " is greater than the maximum value of 12";
            v = 12;
        }

        if (v != mIndicatorSize && !isIndicatorSizeImmutable()) {
            mIndicatorSize = v;
            Q_EMIT IndicatorSizeChanged();
        }
    }

    Q_PROPERTY(int indicatorSize READ indicatorSize WRITE setIndicatorSize NOTIFY IndicatorSizeChanged)
    Q_PROPERTY(bool isIndicatorSizeImmutable READ isIndicatorSizeImmutable CONSTANT)
    Q_PROPERTY(int defaultIndicatorSizeValue READ defaultIndicatorSizeValue CONSTANT)
    /**
      Get Size of the status indicator dots/dashes
    */
    int indicatorSize() const
    {
        return mIndicatorSize;
    }

    /**
      Is Size of the status indicator dots/dashes Immutable
    */
    bool isIndicatorSizeImmutable() const
    {
        return isImmutable(QStringLiteral("IndicatorSize"));
    }

    /**
      Get Size of the status indicator dots/dashes default value
    */
    int defaultIndicatorSizeValue() const
    {
        return defaultIndicatorSizeValue_helper();
    }

    /**
      Set Scale panel thickness proportionally with icon size
    */
    void setSyncPanelThickness(bool v)
    {
        if (v != mSyncPanelThickness && !isSyncPanelThicknessImmutable()) {
            mSyncPanelThickness = v;
            Q_EMIT SyncPanelThicknessChanged();
        }
    }

    Q_PROPERTY(bool syncPanelThickness READ syncPanelThickness WRITE setSyncPanelThickness NOTIFY SyncPanelThicknessChanged)
    Q_PROPERTY(bool isSyncPanelThicknessImmutable READ isSyncPanelThicknessImmutable CONSTANT)
    Q_PROPERTY(bool defaultSyncPanelThicknessValue READ defaultSyncPanelThicknessValue CONSTANT)
    /**
      Get Scale panel thickness proportionally with icon size
    */
    bool syncPanelThickness() const
    {
        return mSyncPanelThickness;
    }

    /**
      Is Scale panel thickness proportionally with icon size Immutable
    */
    bool isSyncPanelThicknessImmutable() const
    {
        return isImmutable(QStringLiteral("SyncPanelThickness"));
    }

    /**
      Get Scale panel thickness proportionally with icon size default value
    */
    bool defaultSyncPanelThicknessValue() const
    {
        return defaultSyncPanelThicknessValue_helper();
    }

    /**
      Set Panel corner radius
    */
    void setCornerRadius(int v)
    {
        if (v < 0) {
            qDebug() << "setCornerRadius: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 100) {
            qDebug() << "setCornerRadius: value " << v << " is greater than the maximum value of 100";
            v = 100;
        }

        if (v != mCornerRadius && !isCornerRadiusImmutable()) {
            mCornerRadius = v;
            Q_EMIT CornerRadiusChanged();
        }
    }

    Q_PROPERTY(int cornerRadius READ cornerRadius WRITE setCornerRadius NOTIFY CornerRadiusChanged)
    Q_PROPERTY(bool isCornerRadiusImmutable READ isCornerRadiusImmutable CONSTANT)
    Q_PROPERTY(int defaultCornerRadiusValue READ defaultCornerRadiusValue CONSTANT)
    /**
      Get Panel corner radius
    */
    int cornerRadius() const
    {
        return mCornerRadius;
    }

    /**
      Is Panel corner radius Immutable
    */
    bool isCornerRadiusImmutable() const
    {
        return isImmutable(QStringLiteral("CornerRadius"));
    }

    /**
      Get Panel corner radius default value
    */
    int defaultCornerRadiusValue() const
    {
        return defaultCornerRadiusValue_helper();
    }

    /**
      Set Whether the dock floats above the screen edge
    */
    void setFloating(bool v)
    {
        if (v != mFloating && !isFloatingImmutable()) {
            mFloating = v;
            Q_EMIT FloatingChanged();
        }
    }

    Q_PROPERTY(bool floating READ floating WRITE setFloating NOTIFY FloatingChanged)
    Q_PROPERTY(bool isFloatingImmutable READ isFloatingImmutable CONSTANT)
    Q_PROPERTY(bool defaultFloatingValue READ defaultFloatingValue CONSTANT)
    /**
      Get Whether the dock floats above the screen edge
    */
    bool floating() const
    {
        return mFloating;
    }

    /**
      Is Whether the dock floats above the screen edge Immutable
    */
    bool isFloatingImmutable() const
    {
        return isImmutable(QStringLiteral("Floating"));
    }

    /**
      Get Whether the dock floats above the screen edge default value
    */
    bool defaultFloatingValue() const
    {
        return defaultFloatingValue_helper();
    }

    /**
      Set Alignment of the dock along the screen edge (0: Center, 1: Left/Top, 2: Right/Bottom)
    */
    void setAlignment(int v)
    {
        if (v < 0) {
            qDebug() << "setAlignment: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setAlignment: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mAlignment && !isAlignmentImmutable()) {
            mAlignment = v;
            Q_EMIT AlignmentChanged();
        }
    }

    Q_PROPERTY(int alignment READ alignment WRITE setAlignment NOTIFY AlignmentChanged)
    Q_PROPERTY(bool isAlignmentImmutable READ isAlignmentImmutable CONSTANT)
    Q_PROPERTY(int defaultAlignmentValue READ defaultAlignmentValue CONSTANT)
    /**
      Get Alignment of the dock along the screen edge (0: Center, 1: Left/Top, 2: Right/Bottom)
    */
    int alignment() const
    {
        return mAlignment;
    }

    /**
      Is Alignment of the dock along the screen edge (0: Center, 1: Left/Top, 2: Right/Bottom) Immutable
    */
    bool isAlignmentImmutable() const
    {
        return isImmutable(QStringLiteral("Alignment"));
    }

    /**
      Get Alignment of the dock along the screen edge (0: Center, 1: Left/Top, 2: Right/Bottom) default value
    */
    int defaultAlignmentValue() const
    {
        return defaultAlignmentValue_helper();
    }

    /**
      Set Dock visibility mode (0=Always, 1=AutoHide, 2=Dodge)
    */
    void setVisibilityMode(int v)
    {
        if (v != mVisibilityMode && !isVisibilityModeImmutable()) {
            mVisibilityMode = v;
            Q_EMIT VisibilityModeChanged();
        }
    }

    Q_PROPERTY(int visibilityMode READ visibilityMode WRITE setVisibilityMode NOTIFY VisibilityModeChanged)
    Q_PROPERTY(bool isVisibilityModeImmutable READ isVisibilityModeImmutable CONSTANT)
    Q_PROPERTY(int defaultVisibilityModeValue READ defaultVisibilityModeValue CONSTANT)
    /**
      Get Dock visibility mode (0=Always, 1=AutoHide, 2=Dodge)
    */
    int visibilityMode() const
    {
        return mVisibilityMode;
    }

    /**
      Is Dock visibility mode (0=Always, 1=AutoHide, 2=Dodge) Immutable
    */
    bool isVisibilityModeImmutable() const
    {
        return isImmutable(QStringLiteral("VisibilityMode"));
    }

    /**
      Get Dock visibility mode (0=Always, 1=AutoHide, 2=Dodge) default value
    */
    int defaultVisibilityModeValue() const
    {
        return defaultVisibilityModeValue_helper();
    }

    /**
      Set Allow the dock panel to shrink smaller than the icons
    */
    void setAllowOverflow(bool v)
    {
        if (v != mAllowOverflow && !isAllowOverflowImmutable()) {
            mAllowOverflow = v;
            Q_EMIT AllowOverflowChanged();
        }
    }

    Q_PROPERTY(bool allowOverflow READ allowOverflow WRITE setAllowOverflow NOTIFY AllowOverflowChanged)
    Q_PROPERTY(bool isAllowOverflowImmutable READ isAllowOverflowImmutable CONSTANT)
    Q_PROPERTY(bool defaultAllowOverflowValue READ defaultAllowOverflowValue CONSTANT)
    /**
      Get Allow the dock panel to shrink smaller than the icons
    */
    bool allowOverflow() const
    {
        return mAllowOverflow;
    }

    /**
      Is Allow the dock panel to shrink smaller than the icons Immutable
    */
    bool isAllowOverflowImmutable() const
    {
        return isImmutable(QStringLiteral("AllowOverflow"));
    }

    /**
      Get Allow the dock panel to shrink smaller than the icons default value
    */
    bool defaultAllowOverflowValue() const
    {
        return defaultAllowOverflowValue_helper();
    }

    /**
      Set Reserve screen space for the dock
    */
    void setReserveSpace(bool v)
    {
        if (v != mReserveSpace && !isReserveSpaceImmutable()) {
            mReserveSpace = v;
            Q_EMIT reserveSpaceChanged();
        }
    }

    Q_PROPERTY(bool reserveSpace READ reserveSpace WRITE setReserveSpace NOTIFY reserveSpaceChanged)
    Q_PROPERTY(bool isReserveSpaceImmutable READ isReserveSpaceImmutable CONSTANT)
    Q_PROPERTY(bool defaultReserveSpaceValue READ defaultReserveSpaceValue CONSTANT)
    /**
      Get Reserve screen space for the dock
    */
    bool reserveSpace() const
    {
        return mReserveSpace;
    }

    /**
      Is Reserve screen space for the dock Immutable
    */
    bool isReserveSpaceImmutable() const
    {
        return isImmutable(QStringLiteral("reserveSpace"));
    }

    /**
      Get Reserve screen space for the dock default value
    */
    bool defaultReserveSpaceValue() const
    {
        return defaultReserveSpaceValue_helper();
    }

    /**
      Set Reserve mode (0=Panel, 1=Icons)
    */
    void setReserveMode(int v)
    {
        if (v < 0) {
            qDebug() << "setReserveMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 1) {
            qDebug() << "setReserveMode: value " << v << " is greater than the maximum value of 1";
            v = 1;
        }

        if (v != mReserveMode && !isReserveModeImmutable()) {
            mReserveMode = v;
            Q_EMIT reserveModeChanged();
        }
    }

    Q_PROPERTY(int reserveMode READ reserveMode WRITE setReserveMode NOTIFY reserveModeChanged)
    Q_PROPERTY(bool isReserveModeImmutable READ isReserveModeImmutable CONSTANT)
    Q_PROPERTY(int defaultReserveModeValue READ defaultReserveModeValue CONSTANT)
    /**
      Get Reserve mode (0=Panel, 1=Icons)
    */
    int reserveMode() const
    {
        return mReserveMode;
    }

    /**
      Is Reserve mode (0=Panel, 1=Icons) Immutable
    */
    bool isReserveModeImmutable() const
    {
        return isImmutable(QStringLiteral("reserveMode"));
    }

    /**
      Get Reserve mode (0=Panel, 1=Icons) default value
    */
    int defaultReserveModeValue() const
    {
        return defaultReserveModeValue_helper();
    }

    /**
      Set Only dodge the active window (false = dodge all overlapping windows)
    */
    void setDodgeActiveOnly(bool v)
    {
        if (v != mDodgeActiveOnly && !isDodgeActiveOnlyImmutable()) {
            mDodgeActiveOnly = v;
            Q_EMIT DodgeActiveOnlyChanged();
        }
    }

    Q_PROPERTY(bool dodgeActiveOnly READ dodgeActiveOnly WRITE setDodgeActiveOnly NOTIFY DodgeActiveOnlyChanged)
    Q_PROPERTY(bool isDodgeActiveOnlyImmutable READ isDodgeActiveOnlyImmutable CONSTANT)
    Q_PROPERTY(bool defaultDodgeActiveOnlyValue READ defaultDodgeActiveOnlyValue CONSTANT)
    /**
      Get Only dodge the active window (false = dodge all overlapping windows)
    */
    bool dodgeActiveOnly() const
    {
        return mDodgeActiveOnly;
    }

    /**
      Is Only dodge the active window (false = dodge all overlapping windows) Immutable
    */
    bool isDodgeActiveOnlyImmutable() const
    {
        return isImmutable(QStringLiteral("DodgeActiveOnly"));
    }

    /**
      Get Only dodge the active window (false = dodge all overlapping windows) default value
    */
    bool defaultDodgeActiveOnlyValue() const
    {
        return defaultDodgeActiveOnlyValue_helper();
    }

    /**
      Set Screen edge (0=Top, 1=Bottom, 2=Left, 3=Right)
    */
    void setEdge(int v)
    {
        if (v != mEdge && !isEdgeImmutable()) {
            mEdge = v;
            Q_EMIT EdgeChanged();
        }
    }

    Q_PROPERTY(int edge READ edge WRITE setEdge NOTIFY EdgeChanged)
    Q_PROPERTY(bool isEdgeImmutable READ isEdgeImmutable CONSTANT)
    Q_PROPERTY(int defaultEdgeValue READ defaultEdgeValue CONSTANT)
    /**
      Get Screen edge (0=Top, 1=Bottom, 2=Left, 3=Right)
    */
    int edge() const
    {
        return mEdge;
    }

    /**
      Is Screen edge (0=Top, 1=Bottom, 2=Left, 3=Right) Immutable
    */
    bool isEdgeImmutable() const
    {
        return isImmutable(QStringLiteral("Edge"));
    }

    /**
      Get Screen edge (0=Top, 1=Bottom, 2=Left, 3=Right) default value
    */
    int defaultEdgeValue() const
    {
        return defaultEdgeValue_helper();
    }

    /**
      Set Delay before showing dock (ms)
    */
    void setShowDelay(int v)
    {
        if (v != mShowDelay && !isShowDelayImmutable()) {
            mShowDelay = v;
            Q_EMIT ShowDelayChanged();
        }
    }

    Q_PROPERTY(int showDelay READ showDelay WRITE setShowDelay NOTIFY ShowDelayChanged)
    Q_PROPERTY(bool isShowDelayImmutable READ isShowDelayImmutable CONSTANT)
    Q_PROPERTY(int defaultShowDelayValue READ defaultShowDelayValue CONSTANT)
    /**
      Get Delay before showing dock (ms)
    */
    int showDelay() const
    {
        return mShowDelay;
    }

    /**
      Is Delay before showing dock (ms) Immutable
    */
    bool isShowDelayImmutable() const
    {
        return isImmutable(QStringLiteral("ShowDelay"));
    }

    /**
      Get Delay before showing dock (ms) default value
    */
    int defaultShowDelayValue() const
    {
        return defaultShowDelayValue_helper();
    }

    /**
      Set Delay before hiding dock (ms)
    */
    void setHideDelay(int v)
    {
        if (v != mHideDelay && !isHideDelayImmutable()) {
            mHideDelay = v;
            Q_EMIT HideDelayChanged();
        }
    }

    Q_PROPERTY(int hideDelay READ hideDelay WRITE setHideDelay NOTIFY HideDelayChanged)
    Q_PROPERTY(bool isHideDelayImmutable READ isHideDelayImmutable CONSTANT)
    Q_PROPERTY(int defaultHideDelayValue READ defaultHideDelayValue CONSTANT)
    /**
      Get Delay before hiding dock (ms)
    */
    int hideDelay() const
    {
        return mHideDelay;
    }

    /**
      Is Delay before hiding dock (ms) Immutable
    */
    bool isHideDelayImmutable() const
    {
        return isImmutable(QStringLiteral("HideDelay"));
    }

    /**
      Get Delay before hiding dock (ms) default value
    */
    int defaultHideDelayValue() const
    {
        return defaultHideDelayValue_helper();
    }

    /**
      Set Background opacity
    */
    void setBackgroundOpacity(double v)
    {
        if (v < 0.3) {
            qDebug() << "setBackgroundOpacity: value " << v << " is less than the minimum value of 0.3";
            v = 0.3;
        }

        if (v > 1.0) {
            qDebug() << "setBackgroundOpacity: value " << v << " is greater than the maximum value of 1.0";
            v = 1.0;
        }

        if (v != mBackgroundOpacity && !isBackgroundOpacityImmutable()) {
            mBackgroundOpacity = v;
            Q_EMIT BackgroundOpacityChanged();
        }
    }

    Q_PROPERTY(double backgroundOpacity READ backgroundOpacity WRITE setBackgroundOpacity NOTIFY BackgroundOpacityChanged)
    Q_PROPERTY(bool isBackgroundOpacityImmutable READ isBackgroundOpacityImmutable CONSTANT)
    Q_PROPERTY(double defaultBackgroundOpacityValue READ defaultBackgroundOpacityValue CONSTANT)
    /**
      Get Background opacity
    */
    double backgroundOpacity() const
    {
        return mBackgroundOpacity;
    }

    /**
      Is Background opacity Immutable
    */
    bool isBackgroundOpacityImmutable() const
    {
        return isImmutable(QStringLiteral("BackgroundOpacity"));
    }

    /**
      Get Background opacity default value
    */
    double defaultBackgroundOpacityValue() const
    {
        return defaultBackgroundOpacityValue_helper();
    }

    /**
      Set Background style (0=Adaptive, 1=Transparent, 2=Solid, 3=Acrylic, 4=Mica)
    */
    void setBackgroundStyle(int v)
    {
        if (v < 0) {
            qDebug() << "setBackgroundStyle: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 4) {
            qDebug() << "setBackgroundStyle: value " << v << " is greater than the maximum value of 4";
            v = 4;
        }

        if (v != mBackgroundStyle && !isBackgroundStyleImmutable()) {
            mBackgroundStyle = v;
            Q_EMIT BackgroundStyleChanged();
        }
    }

    Q_PROPERTY(int backgroundStyle READ backgroundStyle WRITE setBackgroundStyle NOTIFY BackgroundStyleChanged)
    Q_PROPERTY(bool isBackgroundStyleImmutable READ isBackgroundStyleImmutable CONSTANT)
    Q_PROPERTY(int defaultBackgroundStyleValue READ defaultBackgroundStyleValue CONSTANT)
    /**
      Get Background style (0=Adaptive, 1=Transparent, 2=Solid, 3=Acrylic, 4=Mica)
    */
    int backgroundStyle() const
    {
        return mBackgroundStyle;
    }

    /**
      Is Background style (0=Adaptive, 1=Transparent, 2=Solid, 3=Acrylic, 4=Mica) Immutable
    */
    bool isBackgroundStyleImmutable() const
    {
        return isImmutable(QStringLiteral("BackgroundStyle"));
    }

    /**
      Get Background style (0=Adaptive, 1=Transparent, 2=Solid, 3=Acrylic, 4=Mica) default value
    */
    int defaultBackgroundStyleValue() const
    {
        return defaultBackgroundStyleValue_helper();
    }

    /**
      Set Use accent/selection color instead of header color for background
    */
    void setUseAccentColor(bool v)
    {
        if (v != mUseAccentColor && !isUseAccentColorImmutable()) {
            mUseAccentColor = v;
            Q_EMIT UseAccentColorChanged();
        }
    }

    Q_PROPERTY(bool useAccentColor READ useAccentColor WRITE setUseAccentColor NOTIFY UseAccentColorChanged)
    Q_PROPERTY(bool isUseAccentColorImmutable READ isUseAccentColorImmutable CONSTANT)
    Q_PROPERTY(bool defaultUseAccentColorValue READ defaultUseAccentColorValue CONSTANT)
    /**
      Get Use accent/selection color instead of header color for background
    */
    bool useAccentColor() const
    {
        return mUseAccentColor;
    }

    /**
      Is Use accent/selection color instead of header color for background Immutable
    */
    bool isUseAccentColorImmutable() const
    {
        return isImmutable(QStringLiteral("UseAccentColor"));
    }

    /**
      Get Use accent/selection color instead of header color for background default value
    */
    bool defaultUseAccentColorValue() const
    {
        return defaultUseAccentColorValue_helper();
    }

    /**
      Set Use system header color for Tinted style instead of custom tint color
    */
    void setUseSystemColor(bool v)
    {
        if (v != mUseSystemColor && !isUseSystemColorImmutable()) {
            mUseSystemColor = v;
            Q_EMIT UseSystemColorChanged();
        }
    }

    Q_PROPERTY(bool useSystemColor READ useSystemColor WRITE setUseSystemColor NOTIFY UseSystemColorChanged)
    Q_PROPERTY(bool isUseSystemColorImmutable READ isUseSystemColorImmutable CONSTANT)
    Q_PROPERTY(bool defaultUseSystemColorValue READ defaultUseSystemColorValue CONSTANT)
    /**
      Get Use system header color for Tinted style instead of custom tint color
    */
    bool useSystemColor() const
    {
        return mUseSystemColor;
    }

    /**
      Is Use system header color for Tinted style instead of custom tint color Immutable
    */
    bool isUseSystemColorImmutable() const
    {
        return isImmutable(QStringLiteral("UseSystemColor"));
    }

    /**
      Get Use system header color for Tinted style instead of custom tint color default value
    */
    bool defaultUseSystemColorValue() const
    {
        return defaultUseSystemColorValue_helper();
    }

    /**
      Set Custom tint color for Tinted style (hex RGB)
    */
    void setTintColor(const QString &v)
    {
        if (v != mTintColor && !isTintColorImmutable()) {
            mTintColor = v;
            Q_EMIT TintColorChanged();
        }
    }

    Q_PROPERTY(QString tintColor READ tintColor WRITE setTintColor NOTIFY TintColorChanged)
    Q_PROPERTY(bool isTintColorImmutable READ isTintColorImmutable CONSTANT)
    Q_PROPERTY(QString defaultTintColorValue READ defaultTintColorValue CONSTANT)
    /**
      Get Custom tint color for Tinted style (hex RGB)
    */
    QString tintColor() const
    {
        return mTintColor;
    }

    /**
      Is Custom tint color for Tinted style (hex RGB) Immutable
    */
    bool isTintColorImmutable() const
    {
        return isImmutable(QStringLiteral("TintColor"));
    }

    /**
      Get Custom tint color for Tinted style (hex RGB) default value
    */
    QString defaultTintColorValue() const
    {
        return defaultTintColorValue_helper();
    }

    /**
      Set Enable drop shadow behind the dock panel
    */
    void setShadowEnabled(bool v)
    {
        if (v != mShadowEnabled && !isShadowEnabledImmutable()) {
            mShadowEnabled = v;
            Q_EMIT ShadowEnabledChanged();
        }
    }

    Q_PROPERTY(bool shadowEnabled READ shadowEnabled WRITE setShadowEnabled NOTIFY ShadowEnabledChanged)
    Q_PROPERTY(bool isShadowEnabledImmutable READ isShadowEnabledImmutable CONSTANT)
    Q_PROPERTY(bool defaultShadowEnabledValue READ defaultShadowEnabledValue CONSTANT)
    /**
      Get Enable drop shadow behind the dock panel
    */
    bool shadowEnabled() const
    {
        return mShadowEnabled;
    }

    /**
      Is Enable drop shadow behind the dock panel Immutable
    */
    bool isShadowEnabledImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowEnabled"));
    }

    /**
      Get Enable drop shadow behind the dock panel default value
    */
    bool defaultShadowEnabledValue() const
    {
        return defaultShadowEnabledValue_helper();
    }

    /**
      Set Light source X position relative to panel center
    */
    void setShadowLightX(int v)
    {
        if (v < -300) {
            qDebug() << "setShadowLightX: value " << v << " is less than the minimum value of -300";
            v = -300;
        }

        if (v > 300) {
            qDebug() << "setShadowLightX: value " << v << " is greater than the maximum value of 300";
            v = 300;
        }

        if (v != mShadowLightX && !isShadowLightXImmutable()) {
            mShadowLightX = v;
            Q_EMIT ShadowLightXChanged();
        }
    }

    Q_PROPERTY(int shadowLightX READ shadowLightX WRITE setShadowLightX NOTIFY ShadowLightXChanged)
    Q_PROPERTY(bool isShadowLightXImmutable READ isShadowLightXImmutable CONSTANT)
    Q_PROPERTY(int defaultShadowLightXValue READ defaultShadowLightXValue CONSTANT)
    /**
      Get Light source X position relative to panel center
    */
    int shadowLightX() const
    {
        return mShadowLightX;
    }

    /**
      Is Light source X position relative to panel center Immutable
    */
    bool isShadowLightXImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowLightX"));
    }

    /**
      Get Light source X position relative to panel center default value
    */
    int defaultShadowLightXValue() const
    {
        return defaultShadowLightXValue_helper();
    }

    /**
      Set Light source Y position relative to panel center (negative=above)
    */
    void setShadowLightY(int v)
    {
        if (v < -300) {
            qDebug() << "setShadowLightY: value " << v << " is less than the minimum value of -300";
            v = -300;
        }

        if (v > 300) {
            qDebug() << "setShadowLightY: value " << v << " is greater than the maximum value of 300";
            v = 300;
        }

        if (v != mShadowLightY && !isShadowLightYImmutable()) {
            mShadowLightY = v;
            Q_EMIT ShadowLightYChanged();
        }
    }

    Q_PROPERTY(int shadowLightY READ shadowLightY WRITE setShadowLightY NOTIFY ShadowLightYChanged)
    Q_PROPERTY(bool isShadowLightYImmutable READ isShadowLightYImmutable CONSTANT)
    Q_PROPERTY(int defaultShadowLightYValue READ defaultShadowLightYValue CONSTANT)
    /**
      Get Light source Y position relative to panel center (negative=above)
    */
    int shadowLightY() const
    {
        return mShadowLightY;
    }

    /**
      Is Light source Y position relative to panel center (negative=above) Immutable
    */
    bool isShadowLightYImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowLightY"));
    }

    /**
      Get Light source Y position relative to panel center (negative=above) default value
    */
    int defaultShadowLightYValue() const
    {
        return defaultShadowLightYValue_helper();
    }

    /**
      Set Light source height above screen surface
    */
    void setShadowLightZ(int v)
    {
        if (v < 100) {
            qDebug() << "setShadowLightZ: value " << v << " is less than the minimum value of 100";
            v = 100;
        }

        if (v > 2000) {
            qDebug() << "setShadowLightZ: value " << v << " is greater than the maximum value of 2000";
            v = 2000;
        }

        if (v != mShadowLightZ && !isShadowLightZImmutable()) {
            mShadowLightZ = v;
            Q_EMIT ShadowLightZChanged();
        }
    }

    Q_PROPERTY(int shadowLightZ READ shadowLightZ WRITE setShadowLightZ NOTIFY ShadowLightZChanged)
    Q_PROPERTY(bool isShadowLightZImmutable READ isShadowLightZImmutable CONSTANT)
    Q_PROPERTY(int defaultShadowLightZValue READ defaultShadowLightZValue CONSTANT)
    /**
      Get Light source height above screen surface
    */
    int shadowLightZ() const
    {
        return mShadowLightZ;
    }

    /**
      Is Light source height above screen surface Immutable
    */
    bool isShadowLightZImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowLightZ"));
    }

    /**
      Get Light source height above screen surface default value
    */
    int defaultShadowLightZValue() const
    {
        return defaultShadowLightZValue_helper();
    }

    /**
      Set Light source radius (controls shadow softness)
    */
    void setShadowLightRadius(double v)
    {
        if (v < 0.5) {
            qDebug() << "setShadowLightRadius: value " << v << " is less than the minimum value of 0.5";
            v = 0.5;
        }

        if (v > 20.0) {
            qDebug() << "setShadowLightRadius: value " << v << " is greater than the maximum value of 20.0";
            v = 20.0;
        }

        if (v != mShadowLightRadius && !isShadowLightRadiusImmutable()) {
            mShadowLightRadius = v;
            Q_EMIT ShadowLightRadiusChanged();
        }
    }

    Q_PROPERTY(double shadowLightRadius READ shadowLightRadius WRITE setShadowLightRadius NOTIFY ShadowLightRadiusChanged)
    Q_PROPERTY(bool isShadowLightRadiusImmutable READ isShadowLightRadiusImmutable CONSTANT)
    Q_PROPERTY(double defaultShadowLightRadiusValue READ defaultShadowLightRadiusValue CONSTANT)
    /**
      Get Light source radius (controls shadow softness)
    */
    double shadowLightRadius() const
    {
        return mShadowLightRadius;
    }

    /**
      Is Light source radius (controls shadow softness) Immutable
    */
    bool isShadowLightRadiusImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowLightRadius"));
    }

    /**
      Get Light source radius (controls shadow softness) default value
    */
    double defaultShadowLightRadiusValue() const
    {
        return defaultShadowLightRadiusValue_helper();
    }

    /**
      Set Shadow color (hex ARGB)
    */
    void setShadowColor(const QString &v)
    {
        if (v != mShadowColor && !isShadowColorImmutable()) {
            mShadowColor = v;
            Q_EMIT ShadowColorChanged();
        }
    }

    Q_PROPERTY(QString shadowColor READ shadowColor WRITE setShadowColor NOTIFY ShadowColorChanged)
    Q_PROPERTY(bool isShadowColorImmutable READ isShadowColorImmutable CONSTANT)
    Q_PROPERTY(QString defaultShadowColorValue READ defaultShadowColorValue CONSTANT)
    /**
      Get Shadow color (hex ARGB)
    */
    QString shadowColor() const
    {
        return mShadowColor;
    }

    /**
      Is Shadow color (hex ARGB) Immutable
    */
    bool isShadowColorImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowColor"));
    }

    /**
      Get Shadow color (hex ARGB) default value
    */
    QString defaultShadowColorValue() const
    {
        return defaultShadowColorValue_helper();
    }

    /**
      Set Shadow intensity (opacity)
    */
    void setShadowIntensity(double v)
    {
        if (v < 0.0) {
            qDebug() << "setShadowIntensity: value " << v << " is less than the minimum value of 0.0";
            v = 0.0;
        }

        if (v > 1.0) {
            qDebug() << "setShadowIntensity: value " << v << " is greater than the maximum value of 1.0";
            v = 1.0;
        }

        if (v != mShadowIntensity && !isShadowIntensityImmutable()) {
            mShadowIntensity = v;
            Q_EMIT ShadowIntensityChanged();
        }
    }

    Q_PROPERTY(double shadowIntensity READ shadowIntensity WRITE setShadowIntensity NOTIFY ShadowIntensityChanged)
    Q_PROPERTY(bool isShadowIntensityImmutable READ isShadowIntensityImmutable CONSTANT)
    Q_PROPERTY(double defaultShadowIntensityValue READ defaultShadowIntensityValue CONSTANT)
    /**
      Get Shadow intensity (opacity)
    */
    double shadowIntensity() const
    {
        return mShadowIntensity;
    }

    /**
      Is Shadow intensity (opacity) Immutable
    */
    bool isShadowIntensityImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowIntensity"));
    }

    /**
      Get Shadow intensity (opacity) default value
    */
    double defaultShadowIntensityValue() const
    {
        return defaultShadowIntensityValue_helper();
    }

    /**
      Set Panel elevation above screen surface (for shadow projection)
    */
    void setShadowElevation(int v)
    {
        if (v < 1) {
            qDebug() << "setShadowElevation: value " << v << " is less than the minimum value of 1";
            v = 1;
        }

        if (v > 50) {
            qDebug() << "setShadowElevation: value " << v << " is greater than the maximum value of 50";
            v = 50;
        }

        if (v != mShadowElevation && !isShadowElevationImmutable()) {
            mShadowElevation = v;
            Q_EMIT ShadowElevationChanged();
        }
    }

    Q_PROPERTY(int shadowElevation READ shadowElevation WRITE setShadowElevation NOTIFY ShadowElevationChanged)
    Q_PROPERTY(bool isShadowElevationImmutable READ isShadowElevationImmutable CONSTANT)
    Q_PROPERTY(int defaultShadowElevationValue READ defaultShadowElevationValue CONSTANT)
    /**
      Get Panel elevation above screen surface (for shadow projection)
    */
    int shadowElevation() const
    {
        return mShadowElevation;
    }

    /**
      Is Panel elevation above screen surface (for shadow projection) Immutable
    */
    bool isShadowElevationImmutable() const
    {
        return isImmutable(QStringLiteral("ShadowElevation"));
    }

    /**
      Get Panel elevation above screen surface (for shadow projection) default value
    */
    int defaultShadowElevationValue() const
    {
        return defaultShadowElevationValue_helper();
    }

    /**
      Set Enable window preview on hover
    */
    void setPreviewEnabled(bool v)
    {
        if (v != mPreviewEnabled && !isPreviewEnabledImmutable()) {
            mPreviewEnabled = v;
            Q_EMIT PreviewEnabledChanged();
        }
    }

    Q_PROPERTY(bool previewEnabled READ previewEnabled WRITE setPreviewEnabled NOTIFY PreviewEnabledChanged)
    Q_PROPERTY(bool isPreviewEnabledImmutable READ isPreviewEnabledImmutable CONSTANT)
    Q_PROPERTY(bool defaultPreviewEnabledValue READ defaultPreviewEnabledValue CONSTANT)
    /**
      Get Enable window preview on hover
    */
    bool previewEnabled() const
    {
        return mPreviewEnabled;
    }

    /**
      Is Enable window preview on hover Immutable
    */
    bool isPreviewEnabledImmutable() const
    {
        return isImmutable(QStringLiteral("PreviewEnabled"));
    }

    /**
      Get Enable window preview on hover default value
    */
    bool defaultPreviewEnabledValue() const
    {
        return defaultPreviewEnabledValue_helper();
    }

    /**
      Set Preview thumbnail width
    */
    void setPreviewThumbnailSize(int v)
    {
        if (v < 120) {
            qDebug() << "setPreviewThumbnailSize: value " << v << " is less than the minimum value of 120";
            v = 120;
        }

        if (v > 320) {
            qDebug() << "setPreviewThumbnailSize: value " << v << " is greater than the maximum value of 320";
            v = 320;
        }

        if (v != mPreviewThumbnailSize && !isPreviewThumbnailSizeImmutable()) {
            mPreviewThumbnailSize = v;
            Q_EMIT PreviewThumbnailSizeChanged();
        }
    }

    Q_PROPERTY(int previewThumbnailSize READ previewThumbnailSize WRITE setPreviewThumbnailSize NOTIFY PreviewThumbnailSizeChanged)
    Q_PROPERTY(bool isPreviewThumbnailSizeImmutable READ isPreviewThumbnailSizeImmutable CONSTANT)
    Q_PROPERTY(int defaultPreviewThumbnailSizeValue READ defaultPreviewThumbnailSizeValue CONSTANT)
    /**
      Get Preview thumbnail width
    */
    int previewThumbnailSize() const
    {
        return mPreviewThumbnailSize;
    }

    /**
      Is Preview thumbnail width Immutable
    */
    bool isPreviewThumbnailSizeImmutable() const
    {
        return isImmutable(QStringLiteral("PreviewThumbnailSize"));
    }

    /**
      Get Preview thumbnail width default value
    */
    int defaultPreviewThumbnailSizeValue() const
    {
        return defaultPreviewThumbnailSizeValue_helper();
    }

    /**
      Set Delay before showing preview (ms)
    */
    void setPreviewHoverDelay(int v)
    {
        if (v != mPreviewHoverDelay && !isPreviewHoverDelayImmutable()) {
            mPreviewHoverDelay = v;
            Q_EMIT PreviewHoverDelayChanged();
        }
    }

    Q_PROPERTY(int previewHoverDelay READ previewHoverDelay WRITE setPreviewHoverDelay NOTIFY PreviewHoverDelayChanged)
    Q_PROPERTY(bool isPreviewHoverDelayImmutable READ isPreviewHoverDelayImmutable CONSTANT)
    Q_PROPERTY(int defaultPreviewHoverDelayValue READ defaultPreviewHoverDelayValue CONSTANT)
    /**
      Get Delay before showing preview (ms)
    */
    int previewHoverDelay() const
    {
        return mPreviewHoverDelay;
    }

    /**
      Is Delay before showing preview (ms) Immutable
    */
    bool isPreviewHoverDelayImmutable() const
    {
        return isImmutable(QStringLiteral("PreviewHoverDelay"));
    }

    /**
      Get Delay before showing preview (ms) default value
    */
    int defaultPreviewHoverDelayValue() const
    {
        return defaultPreviewHoverDelayValue_helper();
    }

    /**
      Set Delay before hiding preview (ms)
    */
    void setPreviewHideDelay(int v)
    {
        if (v != mPreviewHideDelay && !isPreviewHideDelayImmutable()) {
            mPreviewHideDelay = v;
            Q_EMIT PreviewHideDelayChanged();
        }
    }

    Q_PROPERTY(int previewHideDelay READ previewHideDelay WRITE setPreviewHideDelay NOTIFY PreviewHideDelayChanged)
    Q_PROPERTY(bool isPreviewHideDelayImmutable READ isPreviewHideDelayImmutable CONSTANT)
    Q_PROPERTY(int defaultPreviewHideDelayValue READ defaultPreviewHideDelayValue CONSTANT)
    /**
      Get Delay before hiding preview (ms)
    */
    int previewHideDelay() const
    {
        return mPreviewHideDelay;
    }

    /**
      Is Delay before hiding preview (ms) Immutable
    */
    bool isPreviewHideDelayImmutable() const
    {
        return isImmutable(QStringLiteral("PreviewHideDelay"));
    }

    /**
      Get Delay before hiding preview (ms) default value
    */
    int defaultPreviewHideDelayValue() const
    {
        return defaultPreviewHideDelayValue_helper();
    }

    /**
      Set Attention animation style (0=None, 1=Bounce, 2=Wiggle, 3=Pulse, 4=Glow, 5=DotColor, 6=Blink)
    */
    void setAttentionAnimation(int v)
    {
        if (v < 0) {
            qDebug() << "setAttentionAnimation: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 6) {
            qDebug() << "setAttentionAnimation: value " << v << " is greater than the maximum value of 6";
            v = 6;
        }

        if (v != mAttentionAnimation && !isAttentionAnimationImmutable()) {
            mAttentionAnimation = v;
            Q_EMIT AttentionAnimationChanged();
        }
    }

    Q_PROPERTY(int attentionAnimation READ attentionAnimation WRITE setAttentionAnimation NOTIFY AttentionAnimationChanged)
    Q_PROPERTY(bool isAttentionAnimationImmutable READ isAttentionAnimationImmutable CONSTANT)
    Q_PROPERTY(int defaultAttentionAnimationValue READ defaultAttentionAnimationValue CONSTANT)
    /**
      Get Attention animation style (0=None, 1=Bounce, 2=Wiggle, 3=Pulse, 4=Glow, 5=DotColor, 6=Blink)
    */
    int attentionAnimation() const
    {
        return mAttentionAnimation;
    }

    /**
      Is Attention animation style (0=None, 1=Bounce, 2=Wiggle, 3=Pulse, 4=Glow, 5=DotColor, 6=Blink) Immutable
    */
    bool isAttentionAnimationImmutable() const
    {
        return isImmutable(QStringLiteral("AttentionAnimation"));
    }

    /**
      Get Attention animation style (0=None, 1=Bounce, 2=Wiggle, 3=Pulse, 4=Glow, 5=DotColor, 6=Blink) default value
    */
    int defaultAttentionAnimationValue() const
    {
        return defaultAttentionAnimationValue_helper();
    }

    /**
      Set Duration of attention animation in seconds (0 = infinite)
    */
    void setAttentionAnimationDuration(int v)
    {
        if (v < 0) {
            qDebug() << "setAttentionAnimationDuration: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 60) {
            qDebug() << "setAttentionAnimationDuration: value " << v << " is greater than the maximum value of 60";
            v = 60;
        }

        if (v != mAttentionAnimationDuration && !isAttentionAnimationDurationImmutable()) {
            mAttentionAnimationDuration = v;
            Q_EMIT AttentionAnimationDurationChanged();
        }
    }

    Q_PROPERTY(int attentionAnimationDuration READ attentionAnimationDuration WRITE setAttentionAnimationDuration NOTIFY AttentionAnimationDurationChanged)
    Q_PROPERTY(bool isAttentionAnimationDurationImmutable READ isAttentionAnimationDurationImmutable CONSTANT)
    Q_PROPERTY(int defaultAttentionAnimationDurationValue READ defaultAttentionAnimationDurationValue CONSTANT)
    /**
      Get Duration of attention animation in seconds (0 = infinite)
    */
    int attentionAnimationDuration() const
    {
        return mAttentionAnimationDuration;
    }

    /**
      Is Duration of attention animation in seconds (0 = infinite) Immutable
    */
    bool isAttentionAnimationDurationImmutable() const
    {
        return isImmutable(QStringLiteral("AttentionAnimationDuration"));
    }

    /**
      Get Duration of attention animation in seconds (0 = infinite) default value
    */
    int defaultAttentionAnimationDurationValue() const
    {
        return defaultAttentionAnimationDurationValue_helper();
    }

    /**
      Set Badge display mode (0=Number, 1=Dot, 2=Off)
    */
    void setBadgeDisplayMode(int v)
    {
        if (v < 0) {
            qDebug() << "setBadgeDisplayMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setBadgeDisplayMode: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mBadgeDisplayMode && !isBadgeDisplayModeImmutable()) {
            mBadgeDisplayMode = v;
            Q_EMIT BadgeDisplayModeChanged();
        }
    }

    Q_PROPERTY(int badgeDisplayMode READ badgeDisplayMode WRITE setBadgeDisplayMode NOTIFY BadgeDisplayModeChanged)
    Q_PROPERTY(bool isBadgeDisplayModeImmutable READ isBadgeDisplayModeImmutable CONSTANT)
    Q_PROPERTY(int defaultBadgeDisplayModeValue READ defaultBadgeDisplayModeValue CONSTANT)
    /**
      Get Badge display mode (0=Number, 1=Dot, 2=Off)
    */
    int badgeDisplayMode() const
    {
        return mBadgeDisplayMode;
    }

    /**
      Is Badge display mode (0=Number, 1=Dot, 2=Off) Immutable
    */
    bool isBadgeDisplayModeImmutable() const
    {
        return isImmutable(QStringLiteral("BadgeDisplayMode"));
    }

    /**
      Get Badge display mode (0=Number, 1=Dot, 2=Off) default value
    */
    int defaultBadgeDisplayModeValue() const
    {
        return defaultBadgeDisplayModeValue_helper();
    }

    /**
      Set Monitor mode (0=PrimaryOnly, 1=AllScreens, 2=FollowActive)
    */
    void setMonitorMode(int v)
    {
        if (v < 0) {
            qDebug() << "setMonitorMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setMonitorMode: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mMonitorMode && !isMonitorModeImmutable()) {
            mMonitorMode = v;
            Q_EMIT MonitorModeChanged();
        }
    }

    Q_PROPERTY(int monitorMode READ monitorMode WRITE setMonitorMode NOTIFY MonitorModeChanged)
    Q_PROPERTY(bool isMonitorModeImmutable READ isMonitorModeImmutable CONSTANT)
    Q_PROPERTY(int defaultMonitorModeValue READ defaultMonitorModeValue CONSTANT)
    /**
      Get Monitor mode (0=PrimaryOnly, 1=AllScreens, 2=FollowActive)
    */
    int monitorMode() const
    {
        return mMonitorMode;
    }

    /**
      Is Monitor mode (0=PrimaryOnly, 1=AllScreens, 2=FollowActive) Immutable
    */
    bool isMonitorModeImmutable() const
    {
        return isImmutable(QStringLiteral("MonitorMode"));
    }

    /**
      Get Monitor mode (0=PrimaryOnly, 1=AllScreens, 2=FollowActive) default value
    */
    int defaultMonitorModeValue() const
    {
        return defaultMonitorModeValue_helper();
    }

    /**
      Set Follow active trigger (0=Mouse, 1=Focus, 2=Composite)
    */
    void setFollowActiveTrigger(int v)
    {
        if (v < 0) {
            qDebug() << "setFollowActiveTrigger: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setFollowActiveTrigger: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mFollowActiveTrigger && !isFollowActiveTriggerImmutable()) {
            mFollowActiveTrigger = v;
            Q_EMIT FollowActiveTriggerChanged();
        }
    }

    Q_PROPERTY(int followActiveTrigger READ followActiveTrigger WRITE setFollowActiveTrigger NOTIFY FollowActiveTriggerChanged)
    Q_PROPERTY(bool isFollowActiveTriggerImmutable READ isFollowActiveTriggerImmutable CONSTANT)
    Q_PROPERTY(int defaultFollowActiveTriggerValue READ defaultFollowActiveTriggerValue CONSTANT)
    /**
      Get Follow active trigger (0=Mouse, 1=Focus, 2=Composite)
    */
    int followActiveTrigger() const
    {
        return mFollowActiveTrigger;
    }

    /**
      Is Follow active trigger (0=Mouse, 1=Focus, 2=Composite) Immutable
    */
    bool isFollowActiveTriggerImmutable() const
    {
        return isImmutable(QStringLiteral("FollowActiveTrigger"));
    }

    /**
      Get Follow active trigger (0=Mouse, 1=Focus, 2=Composite) default value
    */
    int defaultFollowActiveTriggerValue() const
    {
        return defaultFollowActiveTriggerValue_helper();
    }

    /**
      Set Screen transition animation (0=Fade, 1=Slide, 2=Instant)
    */
    void setScreenTransition(int v)
    {
        if (v < 0) {
            qDebug() << "setScreenTransition: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setScreenTransition: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mScreenTransition && !isScreenTransitionImmutable()) {
            mScreenTransition = v;
            Q_EMIT ScreenTransitionChanged();
        }
    }

    Q_PROPERTY(int screenTransition READ screenTransition WRITE setScreenTransition NOTIFY ScreenTransitionChanged)
    Q_PROPERTY(bool isScreenTransitionImmutable READ isScreenTransitionImmutable CONSTANT)
    Q_PROPERTY(int defaultScreenTransitionValue READ defaultScreenTransitionValue CONSTANT)
    /**
      Get Screen transition animation (0=Fade, 1=Slide, 2=Instant)
    */
    int screenTransition() const
    {
        return mScreenTransition;
    }

    /**
      Is Screen transition animation (0=Fade, 1=Slide, 2=Instant) Immutable
    */
    bool isScreenTransitionImmutable() const
    {
        return isImmutable(QStringLiteral("ScreenTransition"));
    }

    /**
      Get Screen transition animation (0=Fade, 1=Slide, 2=Instant) default value
    */
    int defaultScreenTransitionValue() const
    {
        return defaultScreenTransitionValue_helper();
    }

    /**
      Set Virtual desktop display mode (0=ShowAll, 1=DimOtherDesktops, 2=CurrentOnly)
    */
    void setVirtualDesktopMode(int v)
    {
        if (v < 0) {
            qDebug() << "setVirtualDesktopMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 2) {
            qDebug() << "setVirtualDesktopMode: value " << v << " is greater than the maximum value of 2";
            v = 2;
        }

        if (v != mVirtualDesktopMode && !isVirtualDesktopModeImmutable()) {
            mVirtualDesktopMode = v;
            Q_EMIT VirtualDesktopModeChanged();
        }
    }

    Q_PROPERTY(int virtualDesktopMode READ virtualDesktopMode WRITE setVirtualDesktopMode NOTIFY VirtualDesktopModeChanged)
    Q_PROPERTY(bool isVirtualDesktopModeImmutable READ isVirtualDesktopModeImmutable CONSTANT)
    Q_PROPERTY(int defaultVirtualDesktopModeValue READ defaultVirtualDesktopModeValue CONSTANT)
    /**
      Get Virtual desktop display mode (0=ShowAll, 1=DimOtherDesktops, 2=CurrentOnly)
    */
    int virtualDesktopMode() const
    {
        return mVirtualDesktopMode;
    }

    /**
      Is Virtual desktop display mode (0=ShowAll, 1=DimOtherDesktops, 2=CurrentOnly) Immutable
    */
    bool isVirtualDesktopModeImmutable() const
    {
        return isImmutable(QStringLiteral("VirtualDesktopMode"));
    }

    /**
      Get Virtual desktop display mode (0=ShowAll, 1=DimOtherDesktops, 2=CurrentOnly) default value
    */
    int defaultVirtualDesktopModeValue() const
    {
        return defaultVirtualDesktopModeValue_helper();
    }

    /**
      Set Opacity for windows on other virtual desktops (DimOtherDesktops mode)
    */
    void setOtherDesktopOpacity(double v)
    {
        if (v < 0.0) {
            qDebug() << "setOtherDesktopOpacity: value " << v << " is less than the minimum value of 0.0";
            v = 0.0;
        }

        if (v > 0.9) {
            qDebug() << "setOtherDesktopOpacity: value " << v << " is greater than the maximum value of 0.9";
            v = 0.9;
        }

        if (v != mOtherDesktopOpacity && !isOtherDesktopOpacityImmutable()) {
            mOtherDesktopOpacity = v;
            Q_EMIT OtherDesktopOpacityChanged();
        }
    }

    Q_PROPERTY(double otherDesktopOpacity READ otherDesktopOpacity WRITE setOtherDesktopOpacity NOTIFY OtherDesktopOpacityChanged)
    Q_PROPERTY(bool isOtherDesktopOpacityImmutable READ isOtherDesktopOpacityImmutable CONSTANT)
    Q_PROPERTY(double defaultOtherDesktopOpacityValue READ defaultOtherDesktopOpacityValue CONSTANT)
    /**
      Get Opacity for windows on other virtual desktops (DimOtherDesktops mode)
    */
    double otherDesktopOpacity() const
    {
        return mOtherDesktopOpacity;
    }

    /**
      Is Opacity for windows on other virtual desktops (DimOtherDesktops mode) Immutable
    */
    bool isOtherDesktopOpacityImmutable() const
    {
        return isImmutable(QStringLiteral("OtherDesktopOpacity"));
    }

    /**
      Get Opacity for windows on other virtual desktops (DimOtherDesktops mode) default value
    */
    double defaultOtherDesktopOpacityValue() const
    {
        return defaultOtherDesktopOpacityValue_helper();
    }

    /**
      Set Pinned launcher URLs
    */
    void setPinnedLaunchers(const QStringList &v)
    {
        if (v != mPinnedLaunchers && !isPinnedLaunchersImmutable()) {
            mPinnedLaunchers = v;
            Q_EMIT PinnedLaunchersChanged();
        }
    }

    Q_PROPERTY(QStringList pinnedLaunchers READ pinnedLaunchers WRITE setPinnedLaunchers NOTIFY PinnedLaunchersChanged)
    Q_PROPERTY(bool isPinnedLaunchersImmutable READ isPinnedLaunchersImmutable CONSTANT)
    Q_PROPERTY(QStringList defaultPinnedLaunchersValue READ defaultPinnedLaunchersValue CONSTANT)
    /**
      Get Pinned launcher URLs
    */
    QStringList pinnedLaunchers() const
    {
        return mPinnedLaunchers;
    }

    /**
      Is Pinned launcher URLs Immutable
    */
    bool isPinnedLaunchersImmutable() const
    {
        return isImmutable(QStringLiteral("PinnedLaunchers"));
    }

    /**
      Get Pinned launcher URLs default value
    */
    QStringList defaultPinnedLaunchersValue() const
    {
        return defaultPinnedLaunchersValue_helper();
    }

    /**
      Set 0=Classic, 1=Dots, 2=Gradient
    */
    void setSeparatorStyle(int v)
    {
        if (v != mSeparatorStyle && !isSeparatorStyleImmutable()) {
            mSeparatorStyle = v;
            Q_EMIT SeparatorStyleChanged();
        }
    }

    Q_PROPERTY(int separatorStyle READ separatorStyle WRITE setSeparatorStyle NOTIFY SeparatorStyleChanged)
    Q_PROPERTY(bool isSeparatorStyleImmutable READ isSeparatorStyleImmutable CONSTANT)
    Q_PROPERTY(int defaultSeparatorStyleValue READ defaultSeparatorStyleValue CONSTANT)
    /**
      Get 0=Classic, 1=Dots, 2=Gradient
    */
    int separatorStyle() const
    {
        return mSeparatorStyle;
    }

    /**
      Is 0=Classic, 1=Dots, 2=Gradient Immutable
    */
    bool isSeparatorStyleImmutable() const
    {
        return isImmutable(QStringLiteral("SeparatorStyle"));
    }

    /**
      Get 0=Classic, 1=Dots, 2=Gradient default value
    */
    int defaultSeparatorStyleValue() const
    {
        return defaultSeparatorStyleValue_helper();
    }

    /**
      Set Thickness of the separator line or dots
    */
    void setSeparatorWidth(int v)
    {
        if (v < 1) {
            qDebug() << "setSeparatorWidth: value " << v << " is less than the minimum value of 1";
            v = 1;
        }

        if (v > 20) {
            qDebug() << "setSeparatorWidth: value " << v << " is greater than the maximum value of 20";
            v = 20;
        }

        if (v != mSeparatorWidth && !isSeparatorWidthImmutable()) {
            mSeparatorWidth = v;
            Q_EMIT SeparatorWidthChanged();
        }
    }

    Q_PROPERTY(int separatorWidth READ separatorWidth WRITE setSeparatorWidth NOTIFY SeparatorWidthChanged)
    Q_PROPERTY(bool isSeparatorWidthImmutable READ isSeparatorWidthImmutable CONSTANT)
    Q_PROPERTY(int defaultSeparatorWidthValue READ defaultSeparatorWidthValue CONSTANT)
    /**
      Get Thickness of the separator line or dots
    */
    int separatorWidth() const
    {
        return mSeparatorWidth;
    }

    /**
      Is Thickness of the separator line or dots Immutable
    */
    bool isSeparatorWidthImmutable() const
    {
        return isImmutable(QStringLiteral("SeparatorWidth"));
    }

    /**
      Get Thickness of the separator line or dots default value
    */
    int defaultSeparatorWidthValue() const
    {
        return defaultSeparatorWidthValue_helper();
    }

    /**
      Set Length of the separator
    */
    void setSeparatorLength(int v)
    {
        if (v < 10) {
            qDebug() << "setSeparatorLength: value " << v << " is less than the minimum value of 10";
            v = 10;
        }

        if (v > 150) {
            qDebug() << "setSeparatorLength: value " << v << " is greater than the maximum value of 150";
            v = 150;
        }

        if (v != mSeparatorLength && !isSeparatorLengthImmutable()) {
            mSeparatorLength = v;
            Q_EMIT SeparatorLengthChanged();
        }
    }

    Q_PROPERTY(int separatorLength READ separatorLength WRITE setSeparatorLength NOTIFY SeparatorLengthChanged)
    Q_PROPERTY(bool isSeparatorLengthImmutable READ isSeparatorLengthImmutable CONSTANT)
    Q_PROPERTY(int defaultSeparatorLengthValue READ defaultSeparatorLengthValue CONSTANT)
    /**
      Get Length of the separator
    */
    int separatorLength() const
    {
        return mSeparatorLength;
    }

    /**
      Is Length of the separator Immutable
    */
    bool isSeparatorLengthImmutable() const
    {
        return isImmutable(QStringLiteral("SeparatorLength"));
    }

    /**
      Get Length of the separator default value
    */
    int defaultSeparatorLengthValue() const
    {
        return defaultSeparatorLengthValue_helper();
    }

    /**
      Set Spacing between dots
    */
    void setSeparatorSpacing(int v)
    {
        if (v < 1) {
            qDebug() << "setSeparatorSpacing: value " << v << " is less than the minimum value of 1";
            v = 1;
        }

        if (v > 15) {
            qDebug() << "setSeparatorSpacing: value " << v << " is greater than the maximum value of 15";
            v = 15;
        }

        if (v != mSeparatorSpacing && !isSeparatorSpacingImmutable()) {
            mSeparatorSpacing = v;
            Q_EMIT SeparatorSpacingChanged();
        }
    }

    Q_PROPERTY(int separatorSpacing READ separatorSpacing WRITE setSeparatorSpacing NOTIFY SeparatorSpacingChanged)
    Q_PROPERTY(bool isSeparatorSpacingImmutable READ isSeparatorSpacingImmutable CONSTANT)
    Q_PROPERTY(int defaultSeparatorSpacingValue READ defaultSeparatorSpacingValue CONSTANT)
    /**
      Get Spacing between dots
    */
    int separatorSpacing() const
    {
        return mSeparatorSpacing;
    }

    /**
      Is Spacing between dots Immutable
    */
    bool isSeparatorSpacingImmutable() const
    {
        return isImmutable(QStringLiteral("SeparatorSpacing"));
    }

    /**
      Get Spacing between dots default value
    */
    int defaultSeparatorSpacingValue() const
    {
        return defaultSeparatorSpacingValue_helper();
    }

    /**
      Set SeparatorOpacity
    */
    void setSeparatorOpacity(double v)
    {
        if (v != mSeparatorOpacity && !isSeparatorOpacityImmutable()) {
            mSeparatorOpacity = v;
            Q_EMIT SeparatorOpacityChanged();
        }
    }

    Q_PROPERTY(double separatorOpacity READ separatorOpacity WRITE setSeparatorOpacity NOTIFY SeparatorOpacityChanged)
    Q_PROPERTY(bool isSeparatorOpacityImmutable READ isSeparatorOpacityImmutable CONSTANT)
    Q_PROPERTY(double defaultSeparatorOpacityValue READ defaultSeparatorOpacityValue CONSTANT)
    /**
      Get SeparatorOpacity
    */
    double separatorOpacity() const
    {
        return mSeparatorOpacity;
    }

    /**
      Is SeparatorOpacity Immutable
    */
    bool isSeparatorOpacityImmutable() const
    {
        return isImmutable(QStringLiteral("SeparatorOpacity"));
    }

    /**
      Get SeparatorOpacity default value
    */
    double defaultSeparatorOpacityValue() const
    {
        return defaultSeparatorOpacityValue_helper();
    }

    /**
      Set Settings UI theme (0=Light, 1=Dark)
    */
    void setSettingsThemeMode(int v)
    {
        if (v < 0) {
            qDebug() << "setSettingsThemeMode: value " << v << " is less than the minimum value of 0";
            v = 0;
        }

        if (v > 1) {
            qDebug() << "setSettingsThemeMode: value " << v << " is greater than the maximum value of 1";
            v = 1;
        }

        if (v != mSettingsThemeMode && !isSettingsThemeModeImmutable()) {
            mSettingsThemeMode = v;
            Q_EMIT SettingsThemeModeChanged();
        }
    }

    Q_PROPERTY(int settingsThemeMode READ settingsThemeMode WRITE setSettingsThemeMode NOTIFY SettingsThemeModeChanged)
    Q_PROPERTY(bool isSettingsThemeModeImmutable READ isSettingsThemeModeImmutable CONSTANT)
    Q_PROPERTY(int defaultSettingsThemeModeValue READ defaultSettingsThemeModeValue CONSTANT)
    /**
      Get Settings UI theme (0=Light, 1=Dark)
    */
    int settingsThemeMode() const
    {
        return mSettingsThemeMode;
    }

    /**
      Is Settings UI theme (0=Light, 1=Dark) Immutable
    */
    bool isSettingsThemeModeImmutable() const
    {
        return isImmutable(QStringLiteral("SettingsThemeMode"));
    }

    /**
      Get Settings UI theme (0=Light, 1=Dark) default value
    */
    int defaultSettingsThemeModeValue() const
    {
        return defaultSettingsThemeModeValue_helper();
    }

    /**
      Set Enable a subtle glowing border around the dock panel
    */
    void setRimLightEnabled(bool v)
    {
        if (v != mRimLightEnabled && !isRimLightEnabledImmutable()) {
            mRimLightEnabled = v;
            Q_EMIT RimLightEnabledChanged();
        }
    }

    Q_PROPERTY(bool rimLightEnabled READ rimLightEnabled WRITE setRimLightEnabled NOTIFY RimLightEnabledChanged)
    Q_PROPERTY(bool isRimLightEnabledImmutable READ isRimLightEnabledImmutable CONSTANT)
    Q_PROPERTY(bool defaultRimLightEnabledValue READ defaultRimLightEnabledValue CONSTANT)
    /**
      Get Enable a subtle glowing border around the dock panel
    */
    bool rimLightEnabled() const
    {
        return mRimLightEnabled;
    }

    /**
      Is Enable a subtle glowing border around the dock panel Immutable
    */
    bool isRimLightEnabledImmutable() const
    {
        return isImmutable(QStringLiteral("RimLightEnabled"));
    }

    /**
      Get Enable a subtle glowing border around the dock panel default value
    */
    bool defaultRimLightEnabledValue() const
    {
        return defaultRimLightEnabledValue_helper();
    }

    /**
      Set Rim light intensity
    */
    void setRimLightOpacity(double v)
    {
        if (v < 0.05) {
            qDebug() << "setRimLightOpacity: value " << v << " is less than the minimum value of 0.05";
            v = 0.05;
        }

        if (v > 0.5) {
            qDebug() << "setRimLightOpacity: value " << v << " is greater than the maximum value of 0.5";
            v = 0.5;
        }

        if (v != mRimLightOpacity && !isRimLightOpacityImmutable()) {
            mRimLightOpacity = v;
            Q_EMIT RimLightOpacityChanged();
        }
    }

    Q_PROPERTY(double rimLightOpacity READ rimLightOpacity WRITE setRimLightOpacity NOTIFY RimLightOpacityChanged)
    Q_PROPERTY(bool isRimLightOpacityImmutable READ isRimLightOpacityImmutable CONSTANT)
    Q_PROPERTY(double defaultRimLightOpacityValue READ defaultRimLightOpacityValue CONSTANT)
    /**
      Get Rim light intensity
    */
    double rimLightOpacity() const
    {
        return mRimLightOpacity;
    }

    /**
      Is Rim light intensity Immutable
    */
    bool isRimLightOpacityImmutable() const
    {
        return isImmutable(QStringLiteral("RimLightOpacity"));
    }

    /**
      Get Rim light intensity default value
    */
    double defaultRimLightOpacityValue() const
    {
        return defaultRimLightOpacityValue_helper();
    }

    enum {
        signalIconSizeChanged = 1,
        signalPanelHeightChanged = 2,
        signalMaxLengthChanged = 3,
        signalPanelLengthModeChanged = 4,
        signalIslandMarginChanged = 5,
        signalIconSpacingChanged = 6,
        signalMaxZoomFactorChanged = 7,
        signalIconNormalizationChanged = 8,
        signalIndicatorOffsetChanged = 9,
        signalIndicatorSizeChanged = 10,
        signalSyncPanelThicknessChanged = 11,
        signalCornerRadiusChanged = 12,
        signalFloatingChanged = 13,
        signalAlignmentChanged = 14,
        signalVisibilityModeChanged = 15,
        signalAllowOverflowChanged = 16,
        signalReserveSpaceChanged = 17,
        signalReserveModeChanged = 18,
        signalDodgeActiveOnlyChanged = 19,
        signalEdgeChanged = 20,
        signalShowDelayChanged = 21,
        signalHideDelayChanged = 22,
        signalBackgroundOpacityChanged = 23,
        signalBackgroundStyleChanged = 24,
        signalUseAccentColorChanged = 25,
        signalUseSystemColorChanged = 26,
        signalTintColorChanged = 27,
        signalShadowEnabledChanged = 28,
        signalShadowLightXChanged = 29,
        signalShadowLightYChanged = 30,
        signalShadowLightZChanged = 31,
        signalShadowLightRadiusChanged = 32,
        signalShadowColorChanged = 33,
        signalShadowIntensityChanged = 34,
        signalShadowElevationChanged = 35,
        signalPreviewEnabledChanged = 36,
        signalPreviewThumbnailSizeChanged = 37,
        signalPreviewHoverDelayChanged = 38,
        signalPreviewHideDelayChanged = 39,
        signalAttentionAnimationChanged = 40,
        signalAttentionAnimationDurationChanged = 41,
        signalBadgeDisplayModeChanged = 42,
        signalMonitorModeChanged = 43,
        signalFollowActiveTriggerChanged = 44,
        signalScreenTransitionChanged = 45,
        signalVirtualDesktopModeChanged = 46,
        signalOtherDesktopOpacityChanged = 47,
        signalPinnedLaunchersChanged = 48,
        signalSeparatorStyleChanged = 49,
        signalSeparatorWidthChanged = 50,
        signalSeparatorLengthChanged = 51,
        signalSeparatorSpacingChanged = 52,
        signalSeparatorOpacityChanged = 53,
        signalSettingsThemeModeChanged = 54,
        signalRimLightEnabledChanged = 55,
        signalRimLightOpacityChanged = 56
    };

Q_SIGNALS:
    void IconSizeChanged();

    void PanelHeightChanged();

    void MaxLengthChanged();

    void PanelLengthModeChanged();

    void IslandMarginChanged();

    void IconSpacingChanged();

    void MaxZoomFactorChanged();

    void IconNormalizationChanged();

    void IndicatorOffsetChanged();

    void IndicatorSizeChanged();

    void SyncPanelThicknessChanged();

    void CornerRadiusChanged();

    void FloatingChanged();

    void AlignmentChanged();

    void VisibilityModeChanged();

    void AllowOverflowChanged();

    void reserveSpaceChanged();

    void reserveModeChanged();

    void DodgeActiveOnlyChanged();

    void EdgeChanged();

    void ShowDelayChanged();

    void HideDelayChanged();

    void BackgroundOpacityChanged();

    void BackgroundStyleChanged();

    void UseAccentColorChanged();

    void UseSystemColorChanged();

    void TintColorChanged();

    void ShadowEnabledChanged();

    void ShadowLightXChanged();

    void ShadowLightYChanged();

    void ShadowLightZChanged();

    void ShadowLightRadiusChanged();

    void ShadowColorChanged();

    void ShadowIntensityChanged();

    void ShadowElevationChanged();

    void PreviewEnabledChanged();

    void PreviewThumbnailSizeChanged();

    void PreviewHoverDelayChanged();

    void PreviewHideDelayChanged();

    void AttentionAnimationChanged();

    void AttentionAnimationDurationChanged();

    void BadgeDisplayModeChanged();

    void MonitorModeChanged();

    void FollowActiveTriggerChanged();

    void ScreenTransitionChanged();

    void VirtualDesktopModeChanged();

    void OtherDesktopOpacityChanged();

    void PinnedLaunchersChanged();

    void SeparatorStyleChanged();

    void SeparatorWidthChanged();

    void SeparatorLengthChanged();

    void SeparatorSpacingChanged();

    void SeparatorOpacityChanged();

    void SettingsThemeModeChanged();

    void RimLightEnabledChanged();

    void RimLightOpacityChanged();

private:
    void itemChanged(quint64 signalFlag);

protected:
    // General
    int mIconSize;
    int defaultIconSizeValue_helper() const;
    int mPanelHeight;
    int defaultPanelHeightValue_helper() const;
    int mMaxLength;
    int defaultMaxLengthValue_helper() const;
    int mPanelLengthMode;
    int defaultPanelLengthModeValue_helper() const;
    int mIslandMargin;
    int defaultIslandMarginValue_helper() const;
    int mIconSpacing;
    int defaultIconSpacingValue_helper() const;
    double mMaxZoomFactor;
    double defaultMaxZoomFactorValue_helper() const;
    bool mIconNormalization;
    bool defaultIconNormalizationValue_helper() const;
    double mIndicatorOffset;
    double defaultIndicatorOffsetValue_helper() const;
    int mIndicatorSize;
    int defaultIndicatorSizeValue_helper() const;
    bool mSyncPanelThickness;
    bool defaultSyncPanelThicknessValue_helper() const;
    int mCornerRadius;
    int defaultCornerRadiusValue_helper() const;
    bool mFloating;
    bool defaultFloatingValue_helper() const;
    int mAlignment;
    int defaultAlignmentValue_helper() const;
    int mVisibilityMode;
    int defaultVisibilityModeValue_helper() const;
    bool mAllowOverflow;
    bool defaultAllowOverflowValue_helper() const;
    bool mReserveSpace;
    bool defaultReserveSpaceValue_helper() const;
    int mReserveMode;
    int defaultReserveModeValue_helper() const;
    bool mDodgeActiveOnly;
    bool defaultDodgeActiveOnlyValue_helper() const;
    int mEdge;
    int defaultEdgeValue_helper() const;
    int mShowDelay;
    int defaultShowDelayValue_helper() const;
    int mHideDelay;
    int defaultHideDelayValue_helper() const;
    double mBackgroundOpacity;
    double defaultBackgroundOpacityValue_helper() const;
    int mBackgroundStyle;
    int defaultBackgroundStyleValue_helper() const;
    bool mUseAccentColor;
    bool defaultUseAccentColorValue_helper() const;
    bool mUseSystemColor;
    bool defaultUseSystemColorValue_helper() const;
    QString mTintColor;
    QString defaultTintColorValue_helper() const;
    bool mShadowEnabled;
    bool defaultShadowEnabledValue_helper() const;
    int mShadowLightX;
    int defaultShadowLightXValue_helper() const;
    int mShadowLightY;
    int defaultShadowLightYValue_helper() const;
    int mShadowLightZ;
    int defaultShadowLightZValue_helper() const;
    double mShadowLightRadius;
    double defaultShadowLightRadiusValue_helper() const;
    QString mShadowColor;
    QString defaultShadowColorValue_helper() const;
    double mShadowIntensity;
    double defaultShadowIntensityValue_helper() const;
    int mShadowElevation;
    int defaultShadowElevationValue_helper() const;
    bool mPreviewEnabled;
    bool defaultPreviewEnabledValue_helper() const;
    int mPreviewThumbnailSize;
    int defaultPreviewThumbnailSizeValue_helper() const;
    int mPreviewHoverDelay;
    int defaultPreviewHoverDelayValue_helper() const;
    int mPreviewHideDelay;
    int defaultPreviewHideDelayValue_helper() const;
    int mAttentionAnimation;
    int defaultAttentionAnimationValue_helper() const;
    int mAttentionAnimationDuration;
    int defaultAttentionAnimationDurationValue_helper() const;
    int mBadgeDisplayMode;
    int defaultBadgeDisplayModeValue_helper() const;
    int mMonitorMode;
    int defaultMonitorModeValue_helper() const;
    int mFollowActiveTrigger;
    int defaultFollowActiveTriggerValue_helper() const;
    int mScreenTransition;
    int defaultScreenTransitionValue_helper() const;
    int mVirtualDesktopMode;
    int defaultVirtualDesktopModeValue_helper() const;
    double mOtherDesktopOpacity;
    double defaultOtherDesktopOpacityValue_helper() const;
    QStringList mPinnedLaunchers;
    QStringList defaultPinnedLaunchersValue_helper() const;
    int mSeparatorStyle;
    int defaultSeparatorStyleValue_helper() const;
    int mSeparatorWidth;
    int defaultSeparatorWidthValue_helper() const;
    int mSeparatorLength;
    int defaultSeparatorLengthValue_helper() const;
    int mSeparatorSpacing;
    int defaultSeparatorSpacingValue_helper() const;
    double mSeparatorOpacity;
    double defaultSeparatorOpacityValue_helper() const;
    int mSettingsThemeMode;
    int defaultSettingsThemeModeValue_helper() const;
    bool mRimLightEnabled;
    bool defaultRimLightEnabledValue_helper() const;
    double mRimLightOpacity;
    double defaultRimLightOpacityValue_helper() const;
};

#endif
