// This file is generated by kconfig_compiler_kf6 from krema.kcfg.
// All changes you do to this file will be lost.

#include "krema.h"

KremaSettings::KremaSettings(QObject *parent)
    : KConfigSkeleton(QStringLiteral("kremarc"))
{
    setParent(parent);
    KConfigCompilerSignallingItem::NotifyFunction notifyFunction = static_cast<KConfigCompilerSignallingItem::NotifyFunction>(&KremaSettings::itemChanged);

    setCurrentGroup(QStringLiteral("General"));

    KConfigCompilerSignallingItem *itemIconSize;
    KConfigSkeleton::ItemInt *innerItemIconSize;
    innerItemIconSize = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("IconSize"), mIconSize, 48);
    itemIconSize = new KConfigCompilerSignallingItem(innerItemIconSize, this, notifyFunction, signalIconSizeChanged);
    innerItemIconSize->setMinValue(12);
    innerItemIconSize->setMaxValue(96);
    addItem(itemIconSize, QStringLiteral("IconSize"));
    KConfigCompilerSignallingItem *itemPanelHeight;
    KConfigSkeleton::ItemInt *innerItemPanelHeight;
    innerItemPanelHeight = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("PanelHeight"), mPanelHeight, 60);
    itemPanelHeight = new KConfigCompilerSignallingItem(innerItemPanelHeight, this, notifyFunction, signalPanelHeightChanged);
    innerItemPanelHeight->setMinValue(10);
    innerItemPanelHeight->setMaxValue(300);
    addItem(itemPanelHeight, QStringLiteral("PanelHeight"));
    KConfigCompilerSignallingItem *itemMaxLength;
    KConfigSkeleton::ItemInt *innerItemMaxLength;
    innerItemMaxLength = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("MaxLength"), mMaxLength, 100);
    itemMaxLength = new KConfigCompilerSignallingItem(innerItemMaxLength, this, notifyFunction, signalMaxLengthChanged);
    innerItemMaxLength->setMinValue(10);
    innerItemMaxLength->setMaxValue(100);
    addItem(itemMaxLength, QStringLiteral("MaxLength"));
    KConfigCompilerSignallingItem *itemPanelLengthMode;
    KConfigSkeleton::ItemInt *innerItemPanelLengthMode;
    innerItemPanelLengthMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("PanelLengthMode"), mPanelLengthMode, 0);
    itemPanelLengthMode = new KConfigCompilerSignallingItem(innerItemPanelLengthMode, this, notifyFunction, signalPanelLengthModeChanged);
    innerItemPanelLengthMode->setMinValue(0);
    innerItemPanelLengthMode->setMaxValue(1);
    addItem(itemPanelLengthMode, QStringLiteral("PanelLengthMode"));
    KConfigCompilerSignallingItem *itemIslandMargin;
    KConfigSkeleton::ItemInt *innerItemIslandMargin;
    innerItemIslandMargin = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("IslandMargin"), mIslandMargin, 8);
    itemIslandMargin = new KConfigCompilerSignallingItem(innerItemIslandMargin, this, notifyFunction, signalIslandMarginChanged);
    innerItemIslandMargin->setMinValue(0);
    innerItemIslandMargin->setMaxValue(20);
    addItem(itemIslandMargin, QStringLiteral("IslandMargin"));
    KConfigCompilerSignallingItem *itemIconSpacing;
    KConfigSkeleton::ItemInt *innerItemIconSpacing;
    innerItemIconSpacing = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("IconSpacing"), mIconSpacing, 4);
    itemIconSpacing = new KConfigCompilerSignallingItem(innerItemIconSpacing, this, notifyFunction, signalIconSpacingChanged);
    innerItemIconSpacing->setMinValue(0);
    innerItemIconSpacing->setMaxValue(16);
    addItem(itemIconSpacing, QStringLiteral("IconSpacing"));
    KConfigCompilerSignallingItem *itemMaxZoomFactor;
    KConfigSkeleton::ItemDouble *innerItemMaxZoomFactor;
    innerItemMaxZoomFactor = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("MaxZoomFactor"), mMaxZoomFactor, 1.6);
    itemMaxZoomFactor = new KConfigCompilerSignallingItem(innerItemMaxZoomFactor, this, notifyFunction, signalMaxZoomFactorChanged);
    innerItemMaxZoomFactor->setMinValue(1.0);
    innerItemMaxZoomFactor->setMaxValue(2.0);
    addItem(itemMaxZoomFactor, QStringLiteral("MaxZoomFactor"));
    KConfigCompilerSignallingItem *itemIconNormalization;
    KConfigSkeleton::ItemBool *innerItemIconNormalization;
    innerItemIconNormalization = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("IconNormalization"), mIconNormalization, true);
    itemIconNormalization = new KConfigCompilerSignallingItem(innerItemIconNormalization, this, notifyFunction, signalIconNormalizationChanged);
    addItem(itemIconNormalization, QStringLiteral("IconNormalization"));
    KConfigCompilerSignallingItem *itemIndicatorOffset;
    KConfigSkeleton::ItemDouble *innerItemIndicatorOffset;
    innerItemIndicatorOffset = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("IndicatorOffset"), mIndicatorOffset, 1.0);
    itemIndicatorOffset = new KConfigCompilerSignallingItem(innerItemIndicatorOffset, this, notifyFunction, signalIndicatorOffsetChanged);
    innerItemIndicatorOffset->setMinValue(0.5);
    innerItemIndicatorOffset->setMaxValue(1.0);
    addItem(itemIndicatorOffset, QStringLiteral("IndicatorOffset"));
    KConfigCompilerSignallingItem *itemIndicatorSize;
    KConfigSkeleton::ItemInt *innerItemIndicatorSize;
    innerItemIndicatorSize = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("IndicatorSize"), mIndicatorSize, 4);
    itemIndicatorSize = new KConfigCompilerSignallingItem(innerItemIndicatorSize, this, notifyFunction, signalIndicatorSizeChanged);
    innerItemIndicatorSize->setMinValue(2);
    innerItemIndicatorSize->setMaxValue(12);
    addItem(itemIndicatorSize, QStringLiteral("IndicatorSize"));
    KConfigCompilerSignallingItem *itemSyncPanelThickness;
    KConfigSkeleton::ItemBool *innerItemSyncPanelThickness;
    innerItemSyncPanelThickness = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("SyncPanelThickness"), mSyncPanelThickness, true);
    itemSyncPanelThickness = new KConfigCompilerSignallingItem(innerItemSyncPanelThickness, this, notifyFunction, signalSyncPanelThicknessChanged);
    addItem(itemSyncPanelThickness, QStringLiteral("SyncPanelThickness"));
    KConfigCompilerSignallingItem *itemCornerRadius;
    KConfigSkeleton::ItemInt *innerItemCornerRadius;
    innerItemCornerRadius = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("CornerRadius"), mCornerRadius, 12);
    itemCornerRadius = new KConfigCompilerSignallingItem(innerItemCornerRadius, this, notifyFunction, signalCornerRadiusChanged);
    innerItemCornerRadius->setMinValue(0);
    innerItemCornerRadius->setMaxValue(100);
    addItem(itemCornerRadius, QStringLiteral("CornerRadius"));
    KConfigCompilerSignallingItem *itemFloating;
    KConfigSkeleton::ItemBool *innerItemFloating;
    innerItemFloating = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("Floating"), mFloating, true);
    itemFloating = new KConfigCompilerSignallingItem(innerItemFloating, this, notifyFunction, signalFloatingChanged);
    addItem(itemFloating, QStringLiteral("Floating"));
    KConfigCompilerSignallingItem *itemAlignment;
    KConfigSkeleton::ItemInt *innerItemAlignment;
    innerItemAlignment = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("Alignment"), mAlignment, 0);
    itemAlignment = new KConfigCompilerSignallingItem(innerItemAlignment, this, notifyFunction, signalAlignmentChanged);
    innerItemAlignment->setMinValue(0);
    innerItemAlignment->setMaxValue(2);
    addItem(itemAlignment, QStringLiteral("Alignment"));
    KConfigCompilerSignallingItem *itemVisibilityMode;
    KConfigSkeleton::ItemInt *innerItemVisibilityMode;
    innerItemVisibilityMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("VisibilityMode"), mVisibilityMode, 0);
    itemVisibilityMode = new KConfigCompilerSignallingItem(innerItemVisibilityMode, this, notifyFunction, signalVisibilityModeChanged);
    addItem(itemVisibilityMode, QStringLiteral("VisibilityMode"));
    KConfigCompilerSignallingItem *itemAllowOverflow;
    KConfigSkeleton::ItemBool *innerItemAllowOverflow;
    innerItemAllowOverflow = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("AllowOverflow"), mAllowOverflow, false);
    itemAllowOverflow = new KConfigCompilerSignallingItem(innerItemAllowOverflow, this, notifyFunction, signalAllowOverflowChanged);
    addItem(itemAllowOverflow, QStringLiteral("AllowOverflow"));
    KConfigCompilerSignallingItem *itemReserveSpace;
    KConfigSkeleton::ItemBool *innerItemReserveSpace;
    innerItemReserveSpace = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("reserveSpace"), mReserveSpace, true);
    itemReserveSpace = new KConfigCompilerSignallingItem(innerItemReserveSpace, this, notifyFunction, signalReserveSpaceChanged);
    addItem(itemReserveSpace, QStringLiteral("reserveSpace"));
    KConfigCompilerSignallingItem *itemReserveMode;
    KConfigSkeleton::ItemInt *innerItemReserveMode;
    innerItemReserveMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("reserveMode"), mReserveMode, 1);
    itemReserveMode = new KConfigCompilerSignallingItem(innerItemReserveMode, this, notifyFunction, signalReserveModeChanged);
    innerItemReserveMode->setMinValue(0);
    innerItemReserveMode->setMaxValue(1);
    addItem(itemReserveMode, QStringLiteral("reserveMode"));
    KConfigCompilerSignallingItem *itemDodgeActiveOnly;
    KConfigSkeleton::ItemBool *innerItemDodgeActiveOnly;
    innerItemDodgeActiveOnly = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("DodgeActiveOnly"), mDodgeActiveOnly, false);
    itemDodgeActiveOnly = new KConfigCompilerSignallingItem(innerItemDodgeActiveOnly, this, notifyFunction, signalDodgeActiveOnlyChanged);
    addItem(itemDodgeActiveOnly, QStringLiteral("DodgeActiveOnly"));
    KConfigCompilerSignallingItem *itemEdge;
    KConfigSkeleton::ItemInt *innerItemEdge;
    innerItemEdge = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("Edge"), mEdge, 1);
    itemEdge = new KConfigCompilerSignallingItem(innerItemEdge, this, notifyFunction, signalEdgeChanged);
    addItem(itemEdge, QStringLiteral("Edge"));
    KConfigCompilerSignallingItem *itemShowDelay;
    KConfigSkeleton::ItemInt *innerItemShowDelay;
    innerItemShowDelay = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ShowDelay"), mShowDelay, 200);
    itemShowDelay = new KConfigCompilerSignallingItem(innerItemShowDelay, this, notifyFunction, signalShowDelayChanged);
    addItem(itemShowDelay, QStringLiteral("ShowDelay"));
    KConfigCompilerSignallingItem *itemHideDelay;
    KConfigSkeleton::ItemInt *innerItemHideDelay;
    innerItemHideDelay = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("HideDelay"), mHideDelay, 400);
    itemHideDelay = new KConfigCompilerSignallingItem(innerItemHideDelay, this, notifyFunction, signalHideDelayChanged);
    addItem(itemHideDelay, QStringLiteral("HideDelay"));
    KConfigCompilerSignallingItem *itemBackgroundOpacity;
    KConfigSkeleton::ItemDouble *innerItemBackgroundOpacity;
    innerItemBackgroundOpacity = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("BackgroundOpacity"), mBackgroundOpacity, 0.6);
    itemBackgroundOpacity = new KConfigCompilerSignallingItem(innerItemBackgroundOpacity, this, notifyFunction, signalBackgroundOpacityChanged);
    innerItemBackgroundOpacity->setMinValue(0.3);
    innerItemBackgroundOpacity->setMaxValue(1.0);
    addItem(itemBackgroundOpacity, QStringLiteral("BackgroundOpacity"));
    KConfigCompilerSignallingItem *itemBackgroundStyle;
    KConfigSkeleton::ItemInt *innerItemBackgroundStyle;
    innerItemBackgroundStyle = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("BackgroundStyle"), mBackgroundStyle, 0);
    itemBackgroundStyle = new KConfigCompilerSignallingItem(innerItemBackgroundStyle, this, notifyFunction, signalBackgroundStyleChanged);
    innerItemBackgroundStyle->setMinValue(0);
    innerItemBackgroundStyle->setMaxValue(4);
    addItem(itemBackgroundStyle, QStringLiteral("BackgroundStyle"));
    KConfigCompilerSignallingItem *itemUseAccentColor;
    KConfigSkeleton::ItemBool *innerItemUseAccentColor;
    innerItemUseAccentColor = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("UseAccentColor"), mUseAccentColor, false);
    itemUseAccentColor = new KConfigCompilerSignallingItem(innerItemUseAccentColor, this, notifyFunction, signalUseAccentColorChanged);
    addItem(itemUseAccentColor, QStringLiteral("UseAccentColor"));
    KConfigCompilerSignallingItem *itemUseSystemColor;
    KConfigSkeleton::ItemBool *innerItemUseSystemColor;
    innerItemUseSystemColor = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("UseSystemColor"), mUseSystemColor, true);
    itemUseSystemColor = new KConfigCompilerSignallingItem(innerItemUseSystemColor, this, notifyFunction, signalUseSystemColorChanged);
    addItem(itemUseSystemColor, QStringLiteral("UseSystemColor"));
    KConfigCompilerSignallingItem *itemTintColor;
    KConfigSkeleton::ItemString *innerItemTintColor;
    innerItemTintColor = new KConfigSkeleton::ItemString(currentGroup(), QStringLiteral("TintColor"), mTintColor, QStringLiteral("#1e3a5f"));
    itemTintColor = new KConfigCompilerSignallingItem(innerItemTintColor, this, notifyFunction, signalTintColorChanged);
    addItem(itemTintColor, QStringLiteral("TintColor"));
    KConfigCompilerSignallingItem *itemShadowEnabled;
    KConfigSkeleton::ItemBool *innerItemShadowEnabled;
    innerItemShadowEnabled = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("ShadowEnabled"), mShadowEnabled, false);
    itemShadowEnabled = new KConfigCompilerSignallingItem(innerItemShadowEnabled, this, notifyFunction, signalShadowEnabledChanged);
    addItem(itemShadowEnabled, QStringLiteral("ShadowEnabled"));
    KConfigCompilerSignallingItem *itemShadowLightX;
    KConfigSkeleton::ItemInt *innerItemShadowLightX;
    innerItemShadowLightX = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ShadowLightX"), mShadowLightX, 0);
    itemShadowLightX = new KConfigCompilerSignallingItem(innerItemShadowLightX, this, notifyFunction, signalShadowLightXChanged);
    innerItemShadowLightX->setMinValue(-300);
    innerItemShadowLightX->setMaxValue(300);
    addItem(itemShadowLightX, QStringLiteral("ShadowLightX"));
    KConfigCompilerSignallingItem *itemShadowLightY;
    KConfigSkeleton::ItemInt *innerItemShadowLightY;
    innerItemShadowLightY = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ShadowLightY"), mShadowLightY, -150);
    itemShadowLightY = new KConfigCompilerSignallingItem(innerItemShadowLightY, this, notifyFunction, signalShadowLightYChanged);
    innerItemShadowLightY->setMinValue(-300);
    innerItemShadowLightY->setMaxValue(300);
    addItem(itemShadowLightY, QStringLiteral("ShadowLightY"));
    KConfigCompilerSignallingItem *itemShadowLightZ;
    KConfigSkeleton::ItemInt *innerItemShadowLightZ;
    innerItemShadowLightZ = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ShadowLightZ"), mShadowLightZ, 500);
    itemShadowLightZ = new KConfigCompilerSignallingItem(innerItemShadowLightZ, this, notifyFunction, signalShadowLightZChanged);
    innerItemShadowLightZ->setMinValue(100);
    innerItemShadowLightZ->setMaxValue(2000);
    addItem(itemShadowLightZ, QStringLiteral("ShadowLightZ"));
    KConfigCompilerSignallingItem *itemShadowLightRadius;
    KConfigSkeleton::ItemDouble *innerItemShadowLightRadius;
    innerItemShadowLightRadius = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("ShadowLightRadius"), mShadowLightRadius, 5.0);
    itemShadowLightRadius = new KConfigCompilerSignallingItem(innerItemShadowLightRadius, this, notifyFunction, signalShadowLightRadiusChanged);
    innerItemShadowLightRadius->setMinValue(0.5);
    innerItemShadowLightRadius->setMaxValue(20.0);
    addItem(itemShadowLightRadius, QStringLiteral("ShadowLightRadius"));
    KConfigCompilerSignallingItem *itemShadowColor;
    KConfigSkeleton::ItemString *innerItemShadowColor;
    innerItemShadowColor = new KConfigSkeleton::ItemString(currentGroup(), QStringLiteral("ShadowColor"), mShadowColor, QStringLiteral("#80000000"));
    itemShadowColor = new KConfigCompilerSignallingItem(innerItemShadowColor, this, notifyFunction, signalShadowColorChanged);
    addItem(itemShadowColor, QStringLiteral("ShadowColor"));
    KConfigCompilerSignallingItem *itemShadowIntensity;
    KConfigSkeleton::ItemDouble *innerItemShadowIntensity;
    innerItemShadowIntensity = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("ShadowIntensity"), mShadowIntensity, 0.3);
    itemShadowIntensity = new KConfigCompilerSignallingItem(innerItemShadowIntensity, this, notifyFunction, signalShadowIntensityChanged);
    innerItemShadowIntensity->setMinValue(0.0);
    innerItemShadowIntensity->setMaxValue(1.0);
    addItem(itemShadowIntensity, QStringLiteral("ShadowIntensity"));
    KConfigCompilerSignallingItem *itemShadowElevation;
    KConfigSkeleton::ItemInt *innerItemShadowElevation;
    innerItemShadowElevation = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ShadowElevation"), mShadowElevation, 15);
    itemShadowElevation = new KConfigCompilerSignallingItem(innerItemShadowElevation, this, notifyFunction, signalShadowElevationChanged);
    innerItemShadowElevation->setMinValue(1);
    innerItemShadowElevation->setMaxValue(50);
    addItem(itemShadowElevation, QStringLiteral("ShadowElevation"));
    KConfigCompilerSignallingItem *itemPreviewEnabled;
    KConfigSkeleton::ItemBool *innerItemPreviewEnabled;
    innerItemPreviewEnabled = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("PreviewEnabled"), mPreviewEnabled, true);
    itemPreviewEnabled = new KConfigCompilerSignallingItem(innerItemPreviewEnabled, this, notifyFunction, signalPreviewEnabledChanged);
    addItem(itemPreviewEnabled, QStringLiteral("PreviewEnabled"));
    KConfigCompilerSignallingItem *itemPreviewThumbnailSize;
    KConfigSkeleton::ItemInt *innerItemPreviewThumbnailSize;
    innerItemPreviewThumbnailSize = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("PreviewThumbnailSize"), mPreviewThumbnailSize, 200);
    itemPreviewThumbnailSize = new KConfigCompilerSignallingItem(innerItemPreviewThumbnailSize, this, notifyFunction, signalPreviewThumbnailSizeChanged);
    innerItemPreviewThumbnailSize->setMinValue(120);
    innerItemPreviewThumbnailSize->setMaxValue(320);
    addItem(itemPreviewThumbnailSize, QStringLiteral("PreviewThumbnailSize"));
    KConfigCompilerSignallingItem *itemPreviewHoverDelay;
    KConfigSkeleton::ItemInt *innerItemPreviewHoverDelay;
    innerItemPreviewHoverDelay = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("PreviewHoverDelay"), mPreviewHoverDelay, 500);
    itemPreviewHoverDelay = new KConfigCompilerSignallingItem(innerItemPreviewHoverDelay, this, notifyFunction, signalPreviewHoverDelayChanged);
    addItem(itemPreviewHoverDelay, QStringLiteral("PreviewHoverDelay"));
    KConfigCompilerSignallingItem *itemPreviewHideDelay;
    KConfigSkeleton::ItemInt *innerItemPreviewHideDelay;
    innerItemPreviewHideDelay = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("PreviewHideDelay"), mPreviewHideDelay, 200);
    itemPreviewHideDelay = new KConfigCompilerSignallingItem(innerItemPreviewHideDelay, this, notifyFunction, signalPreviewHideDelayChanged);
    addItem(itemPreviewHideDelay, QStringLiteral("PreviewHideDelay"));
    KConfigCompilerSignallingItem *itemAttentionAnimation;
    KConfigSkeleton::ItemInt *innerItemAttentionAnimation;
    innerItemAttentionAnimation = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("AttentionAnimation"), mAttentionAnimation, 2);
    itemAttentionAnimation = new KConfigCompilerSignallingItem(innerItemAttentionAnimation, this, notifyFunction, signalAttentionAnimationChanged);
    innerItemAttentionAnimation->setMinValue(0);
    innerItemAttentionAnimation->setMaxValue(6);
    addItem(itemAttentionAnimation, QStringLiteral("AttentionAnimation"));
    KConfigCompilerSignallingItem *itemAttentionAnimationDuration;
    KConfigSkeleton::ItemInt *innerItemAttentionAnimationDuration;
    innerItemAttentionAnimationDuration =
        new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("AttentionAnimationDuration"), mAttentionAnimationDuration, 5);
    itemAttentionAnimationDuration =
        new KConfigCompilerSignallingItem(innerItemAttentionAnimationDuration, this, notifyFunction, signalAttentionAnimationDurationChanged);
    innerItemAttentionAnimationDuration->setMinValue(0);
    innerItemAttentionAnimationDuration->setMaxValue(60);
    addItem(itemAttentionAnimationDuration, QStringLiteral("AttentionAnimationDuration"));
    KConfigCompilerSignallingItem *itemBadgeDisplayMode;
    KConfigSkeleton::ItemInt *innerItemBadgeDisplayMode;
    innerItemBadgeDisplayMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("BadgeDisplayMode"), mBadgeDisplayMode, 0);
    itemBadgeDisplayMode = new KConfigCompilerSignallingItem(innerItemBadgeDisplayMode, this, notifyFunction, signalBadgeDisplayModeChanged);
    innerItemBadgeDisplayMode->setMinValue(0);
    innerItemBadgeDisplayMode->setMaxValue(2);
    addItem(itemBadgeDisplayMode, QStringLiteral("BadgeDisplayMode"));
    KConfigCompilerSignallingItem *itemMonitorMode;
    KConfigSkeleton::ItemInt *innerItemMonitorMode;
    innerItemMonitorMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("MonitorMode"), mMonitorMode, 0);
    itemMonitorMode = new KConfigCompilerSignallingItem(innerItemMonitorMode, this, notifyFunction, signalMonitorModeChanged);
    innerItemMonitorMode->setMinValue(0);
    innerItemMonitorMode->setMaxValue(2);
    addItem(itemMonitorMode, QStringLiteral("MonitorMode"));
    KConfigCompilerSignallingItem *itemFollowActiveTrigger;
    KConfigSkeleton::ItemInt *innerItemFollowActiveTrigger;
    innerItemFollowActiveTrigger = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("FollowActiveTrigger"), mFollowActiveTrigger, 1);
    itemFollowActiveTrigger = new KConfigCompilerSignallingItem(innerItemFollowActiveTrigger, this, notifyFunction, signalFollowActiveTriggerChanged);
    innerItemFollowActiveTrigger->setMinValue(0);
    innerItemFollowActiveTrigger->setMaxValue(2);
    addItem(itemFollowActiveTrigger, QStringLiteral("FollowActiveTrigger"));
    KConfigCompilerSignallingItem *itemScreenTransition;
    KConfigSkeleton::ItemInt *innerItemScreenTransition;
    innerItemScreenTransition = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("ScreenTransition"), mScreenTransition, 0);
    itemScreenTransition = new KConfigCompilerSignallingItem(innerItemScreenTransition, this, notifyFunction, signalScreenTransitionChanged);
    innerItemScreenTransition->setMinValue(0);
    innerItemScreenTransition->setMaxValue(2);
    addItem(itemScreenTransition, QStringLiteral("ScreenTransition"));
    KConfigCompilerSignallingItem *itemVirtualDesktopMode;
    KConfigSkeleton::ItemInt *innerItemVirtualDesktopMode;
    innerItemVirtualDesktopMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("VirtualDesktopMode"), mVirtualDesktopMode, 1);
    itemVirtualDesktopMode = new KConfigCompilerSignallingItem(innerItemVirtualDesktopMode, this, notifyFunction, signalVirtualDesktopModeChanged);
    innerItemVirtualDesktopMode->setMinValue(0);
    innerItemVirtualDesktopMode->setMaxValue(2);
    addItem(itemVirtualDesktopMode, QStringLiteral("VirtualDesktopMode"));
    KConfigCompilerSignallingItem *itemOtherDesktopOpacity;
    KConfigSkeleton::ItemDouble *innerItemOtherDesktopOpacity;
    innerItemOtherDesktopOpacity = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("OtherDesktopOpacity"), mOtherDesktopOpacity, 0.4);
    itemOtherDesktopOpacity = new KConfigCompilerSignallingItem(innerItemOtherDesktopOpacity, this, notifyFunction, signalOtherDesktopOpacityChanged);
    innerItemOtherDesktopOpacity->setMinValue(0.0);
    innerItemOtherDesktopOpacity->setMaxValue(0.9);
    addItem(itemOtherDesktopOpacity, QStringLiteral("OtherDesktopOpacity"));
    QStringList defaultPinnedLaunchers;
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.dolphin.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.konsole.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.kate.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:systemsettings.desktop"));

    KConfigCompilerSignallingItem *itemPinnedLaunchers;
    KConfigSkeleton::ItemStringList *innerItemPinnedLaunchers;
    innerItemPinnedLaunchers = new KConfigSkeleton::ItemStringList(currentGroup(), QStringLiteral("PinnedLaunchers"), mPinnedLaunchers, defaultPinnedLaunchers);
    itemPinnedLaunchers = new KConfigCompilerSignallingItem(innerItemPinnedLaunchers, this, notifyFunction, signalPinnedLaunchersChanged);
    addItem(itemPinnedLaunchers, QStringLiteral("PinnedLaunchers"));
    KConfigCompilerSignallingItem *itemSeparatorStyle;
    KConfigSkeleton::ItemInt *innerItemSeparatorStyle;
    innerItemSeparatorStyle = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("SeparatorStyle"), mSeparatorStyle, 0);
    itemSeparatorStyle = new KConfigCompilerSignallingItem(innerItemSeparatorStyle, this, notifyFunction, signalSeparatorStyleChanged);
    addItem(itemSeparatorStyle, QStringLiteral("SeparatorStyle"));
    KConfigCompilerSignallingItem *itemSeparatorWidth;
    KConfigSkeleton::ItemInt *innerItemSeparatorWidth;
    innerItemSeparatorWidth = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("SeparatorWidth"), mSeparatorWidth, 3);
    itemSeparatorWidth = new KConfigCompilerSignallingItem(innerItemSeparatorWidth, this, notifyFunction, signalSeparatorWidthChanged);
    innerItemSeparatorWidth->setMinValue(1);
    innerItemSeparatorWidth->setMaxValue(20);
    addItem(itemSeparatorWidth, QStringLiteral("SeparatorWidth"));
    KConfigCompilerSignallingItem *itemSeparatorLength;
    KConfigSkeleton::ItemInt *innerItemSeparatorLength;
    innerItemSeparatorLength = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("SeparatorLength"), mSeparatorLength, 40);
    itemSeparatorLength = new KConfigCompilerSignallingItem(innerItemSeparatorLength, this, notifyFunction, signalSeparatorLengthChanged);
    innerItemSeparatorLength->setMinValue(10);
    innerItemSeparatorLength->setMaxValue(150);
    addItem(itemSeparatorLength, QStringLiteral("SeparatorLength"));
    KConfigCompilerSignallingItem *itemSeparatorSpacing;
    KConfigSkeleton::ItemInt *innerItemSeparatorSpacing;
    innerItemSeparatorSpacing = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("SeparatorSpacing"), mSeparatorSpacing, 4);
    itemSeparatorSpacing = new KConfigCompilerSignallingItem(innerItemSeparatorSpacing, this, notifyFunction, signalSeparatorSpacingChanged);
    innerItemSeparatorSpacing->setMinValue(1);
    innerItemSeparatorSpacing->setMaxValue(15);
    addItem(itemSeparatorSpacing, QStringLiteral("SeparatorSpacing"));
    KConfigCompilerSignallingItem *itemSeparatorOpacity;
    KConfigSkeleton::ItemDouble *innerItemSeparatorOpacity;
    innerItemSeparatorOpacity = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("SeparatorOpacity"), mSeparatorOpacity, 0.5);
    itemSeparatorOpacity = new KConfigCompilerSignallingItem(innerItemSeparatorOpacity, this, notifyFunction, signalSeparatorOpacityChanged);
    addItem(itemSeparatorOpacity, QStringLiteral("SeparatorOpacity"));
    KConfigCompilerSignallingItem *itemSettingsThemeMode;
    KConfigSkeleton::ItemInt *innerItemSettingsThemeMode;
    innerItemSettingsThemeMode = new KConfigSkeleton::ItemInt(currentGroup(), QStringLiteral("SettingsThemeMode"), mSettingsThemeMode, 1);
    itemSettingsThemeMode = new KConfigCompilerSignallingItem(innerItemSettingsThemeMode, this, notifyFunction, signalSettingsThemeModeChanged);
    innerItemSettingsThemeMode->setMinValue(0);
    innerItemSettingsThemeMode->setMaxValue(1);
    addItem(itemSettingsThemeMode, QStringLiteral("SettingsThemeMode"));
    KConfigCompilerSignallingItem *itemRimLightEnabled;
    KConfigSkeleton::ItemBool *innerItemRimLightEnabled;
    innerItemRimLightEnabled = new KConfigSkeleton::ItemBool(currentGroup(), QStringLiteral("RimLightEnabled"), mRimLightEnabled, false);
    itemRimLightEnabled = new KConfigCompilerSignallingItem(innerItemRimLightEnabled, this, notifyFunction, signalRimLightEnabledChanged);
    addItem(itemRimLightEnabled, QStringLiteral("RimLightEnabled"));
    KConfigCompilerSignallingItem *itemRimLightOpacity;
    KConfigSkeleton::ItemDouble *innerItemRimLightOpacity;
    innerItemRimLightOpacity = new KConfigSkeleton::ItemDouble(currentGroup(), QStringLiteral("RimLightOpacity"), mRimLightOpacity, 0.1);
    itemRimLightOpacity = new KConfigCompilerSignallingItem(innerItemRimLightOpacity, this, notifyFunction, signalRimLightOpacityChanged);
    innerItemRimLightOpacity->setMinValue(0.05);
    innerItemRimLightOpacity->setMaxValue(0.5);
    addItem(itemRimLightOpacity, QStringLiteral("RimLightOpacity"));
}

int KremaSettings::defaultIconSizeValue_helper() const
{
    return 48;
}

int KremaSettings::defaultPanelHeightValue_helper() const
{
    return 60;
}

int KremaSettings::defaultMaxLengthValue_helper() const
{
    return 100;
}

int KremaSettings::defaultPanelLengthModeValue_helper() const
{
    return 0;
}

int KremaSettings::defaultIslandMarginValue_helper() const
{
    return 8;
}

int KremaSettings::defaultIconSpacingValue_helper() const
{
    return 4;
}

double KremaSettings::defaultMaxZoomFactorValue_helper() const
{
    return 1.6;
}

bool KremaSettings::defaultIconNormalizationValue_helper() const
{
    return true;
}

double KremaSettings::defaultIndicatorOffsetValue_helper() const
{
    return 1.0;
}

int KremaSettings::defaultIndicatorSizeValue_helper() const
{
    return 4;
}

bool KremaSettings::defaultSyncPanelThicknessValue_helper() const
{
    return true;
}

int KremaSettings::defaultCornerRadiusValue_helper() const
{
    return 12;
}

bool KremaSettings::defaultFloatingValue_helper() const
{
    return true;
}

int KremaSettings::defaultAlignmentValue_helper() const
{
    return 0;
}

int KremaSettings::defaultVisibilityModeValue_helper() const
{
    return 0;
}

bool KremaSettings::defaultAllowOverflowValue_helper() const
{
    return false;
}

bool KremaSettings::defaultReserveSpaceValue_helper() const
{
    return true;
}

int KremaSettings::defaultReserveModeValue_helper() const
{
    return 1;
}

bool KremaSettings::defaultDodgeActiveOnlyValue_helper() const
{
    return false;
}

int KremaSettings::defaultEdgeValue_helper() const
{
    return 1;
}

int KremaSettings::defaultShowDelayValue_helper() const
{
    return 200;
}

int KremaSettings::defaultHideDelayValue_helper() const
{
    return 400;
}

double KremaSettings::defaultBackgroundOpacityValue_helper() const
{
    return 0.6;
}

int KremaSettings::defaultBackgroundStyleValue_helper() const
{
    return 0;
}

bool KremaSettings::defaultUseAccentColorValue_helper() const
{
    return false;
}

bool KremaSettings::defaultUseSystemColorValue_helper() const
{
    return true;
}

QString KremaSettings::defaultTintColorValue_helper() const
{
    return QStringLiteral("#1e3a5f");
}

bool KremaSettings::defaultShadowEnabledValue_helper() const
{
    return false;
}

int KremaSettings::defaultShadowLightXValue_helper() const
{
    return 0;
}

int KremaSettings::defaultShadowLightYValue_helper() const
{
    return -150;
}

int KremaSettings::defaultShadowLightZValue_helper() const
{
    return 500;
}

double KremaSettings::defaultShadowLightRadiusValue_helper() const
{
    return 5.0;
}

QString KremaSettings::defaultShadowColorValue_helper() const
{
    return QStringLiteral("#80000000");
}

double KremaSettings::defaultShadowIntensityValue_helper() const
{
    return 0.3;
}

int KremaSettings::defaultShadowElevationValue_helper() const
{
    return 15;
}

bool KremaSettings::defaultPreviewEnabledValue_helper() const
{
    return true;
}

int KremaSettings::defaultPreviewThumbnailSizeValue_helper() const
{
    return 200;
}

int KremaSettings::defaultPreviewHoverDelayValue_helper() const
{
    return 500;
}

int KremaSettings::defaultPreviewHideDelayValue_helper() const
{
    return 200;
}

int KremaSettings::defaultAttentionAnimationValue_helper() const
{
    return 2;
}

int KremaSettings::defaultAttentionAnimationDurationValue_helper() const
{
    return 5;
}

int KremaSettings::defaultBadgeDisplayModeValue_helper() const
{
    return 0;
}

int KremaSettings::defaultMonitorModeValue_helper() const
{
    return 0;
}

int KremaSettings::defaultFollowActiveTriggerValue_helper() const
{
    return 1;
}

int KremaSettings::defaultScreenTransitionValue_helper() const
{
    return 0;
}

int KremaSettings::defaultVirtualDesktopModeValue_helper() const
{
    return 1;
}

double KremaSettings::defaultOtherDesktopOpacityValue_helper() const
{
    return 0.4;
}

QStringList KremaSettings::defaultPinnedLaunchersValue_helper() const
{
    QStringList defaultPinnedLaunchers;
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.dolphin.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.konsole.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:org.kde.kate.desktop"));
    defaultPinnedLaunchers.append(QString::fromUtf8("applications:systemsettings.desktop"));

    return defaultPinnedLaunchers;
}

int KremaSettings::defaultSeparatorStyleValue_helper() const
{
    return 0;
}

int KremaSettings::defaultSeparatorWidthValue_helper() const
{
    return 3;
}

int KremaSettings::defaultSeparatorLengthValue_helper() const
{
    return 40;
}

int KremaSettings::defaultSeparatorSpacingValue_helper() const
{
    return 4;
}

double KremaSettings::defaultSeparatorOpacityValue_helper() const
{
    return 0.5;
}

int KremaSettings::defaultSettingsThemeModeValue_helper() const
{
    return 1;
}

bool KremaSettings::defaultRimLightEnabledValue_helper() const
{
    return false;
}

double KremaSettings::defaultRimLightOpacityValue_helper() const
{
    return 0.1;
}

KremaSettings::~KremaSettings()
{
}

void KremaSettings::itemChanged(quint64 signalFlag)
{
    switch (signalFlag) {
    case signalIconSizeChanged:
        Q_EMIT IconSizeChanged();
        break;
    case signalPanelHeightChanged:
        Q_EMIT PanelHeightChanged();
        break;
    case signalMaxLengthChanged:
        Q_EMIT MaxLengthChanged();
        break;
    case signalPanelLengthModeChanged:
        Q_EMIT PanelLengthModeChanged();
        break;
    case signalIslandMarginChanged:
        Q_EMIT IslandMarginChanged();
        break;
    case signalIconSpacingChanged:
        Q_EMIT IconSpacingChanged();
        break;
    case signalMaxZoomFactorChanged:
        Q_EMIT MaxZoomFactorChanged();
        break;
    case signalIconNormalizationChanged:
        Q_EMIT IconNormalizationChanged();
        break;
    case signalIndicatorOffsetChanged:
        Q_EMIT IndicatorOffsetChanged();
        break;
    case signalIndicatorSizeChanged:
        Q_EMIT IndicatorSizeChanged();
        break;
    case signalSyncPanelThicknessChanged:
        Q_EMIT SyncPanelThicknessChanged();
        break;
    case signalCornerRadiusChanged:
        Q_EMIT CornerRadiusChanged();
        break;
    case signalFloatingChanged:
        Q_EMIT FloatingChanged();
        break;
    case signalAlignmentChanged:
        Q_EMIT AlignmentChanged();
        break;
    case signalVisibilityModeChanged:
        Q_EMIT VisibilityModeChanged();
        break;
    case signalAllowOverflowChanged:
        Q_EMIT AllowOverflowChanged();
        break;
    case signalReserveSpaceChanged:
        Q_EMIT reserveSpaceChanged();
        break;
    case signalReserveModeChanged:
        Q_EMIT reserveModeChanged();
        break;
    case signalDodgeActiveOnlyChanged:
        Q_EMIT DodgeActiveOnlyChanged();
        break;
    case signalEdgeChanged:
        Q_EMIT EdgeChanged();
        break;
    case signalShowDelayChanged:
        Q_EMIT ShowDelayChanged();
        break;
    case signalHideDelayChanged:
        Q_EMIT HideDelayChanged();
        break;
    case signalBackgroundOpacityChanged:
        Q_EMIT BackgroundOpacityChanged();
        break;
    case signalBackgroundStyleChanged:
        Q_EMIT BackgroundStyleChanged();
        break;
    case signalUseAccentColorChanged:
        Q_EMIT UseAccentColorChanged();
        break;
    case signalUseSystemColorChanged:
        Q_EMIT UseSystemColorChanged();
        break;
    case signalTintColorChanged:
        Q_EMIT TintColorChanged();
        break;
    case signalShadowEnabledChanged:
        Q_EMIT ShadowEnabledChanged();
        break;
    case signalShadowLightXChanged:
        Q_EMIT ShadowLightXChanged();
        break;
    case signalShadowLightYChanged:
        Q_EMIT ShadowLightYChanged();
        break;
    case signalShadowLightZChanged:
        Q_EMIT ShadowLightZChanged();
        break;
    case signalShadowLightRadiusChanged:
        Q_EMIT ShadowLightRadiusChanged();
        break;
    case signalShadowColorChanged:
        Q_EMIT ShadowColorChanged();
        break;
    case signalShadowIntensityChanged:
        Q_EMIT ShadowIntensityChanged();
        break;
    case signalShadowElevationChanged:
        Q_EMIT ShadowElevationChanged();
        break;
    case signalPreviewEnabledChanged:
        Q_EMIT PreviewEnabledChanged();
        break;
    case signalPreviewThumbnailSizeChanged:
        Q_EMIT PreviewThumbnailSizeChanged();
        break;
    case signalPreviewHoverDelayChanged:
        Q_EMIT PreviewHoverDelayChanged();
        break;
    case signalPreviewHideDelayChanged:
        Q_EMIT PreviewHideDelayChanged();
        break;
    case signalAttentionAnimationChanged:
        Q_EMIT AttentionAnimationChanged();
        break;
    case signalAttentionAnimationDurationChanged:
        Q_EMIT AttentionAnimationDurationChanged();
        break;
    case signalBadgeDisplayModeChanged:
        Q_EMIT BadgeDisplayModeChanged();
        break;
    case signalMonitorModeChanged:
        Q_EMIT MonitorModeChanged();
        break;
    case signalFollowActiveTriggerChanged:
        Q_EMIT FollowActiveTriggerChanged();
        break;
    case signalScreenTransitionChanged:
        Q_EMIT ScreenTransitionChanged();
        break;
    case signalVirtualDesktopModeChanged:
        Q_EMIT VirtualDesktopModeChanged();
        break;
    case signalOtherDesktopOpacityChanged:
        Q_EMIT OtherDesktopOpacityChanged();
        break;
    case signalPinnedLaunchersChanged:
        Q_EMIT PinnedLaunchersChanged();
        break;
    case signalSeparatorStyleChanged:
        Q_EMIT SeparatorStyleChanged();
        break;
    case signalSeparatorWidthChanged:
        Q_EMIT SeparatorWidthChanged();
        break;
    case signalSeparatorLengthChanged:
        Q_EMIT SeparatorLengthChanged();
        break;
    case signalSeparatorSpacingChanged:
        Q_EMIT SeparatorSpacingChanged();
        break;
    case signalSeparatorOpacityChanged:
        Q_EMIT SeparatorOpacityChanged();
        break;
    case signalSettingsThemeModeChanged:
        Q_EMIT SettingsThemeModeChanged();
        break;
    case signalRimLightEnabledChanged:
        Q_EMIT RimLightEnabledChanged();
        break;
    case signalRimLightOpacityChanged:
        Q_EMIT RimLightOpacityChanged();
        break;
    }
}
