add_test( [==[Parabolic zoom factor]==] /home/clem/Projects/krema/build_test_qt6_dir/bin/krema_unit_tests [==[Parabolic zoom factor]==]  )
set_tests_properties( [==[Parabolic zoom factor]==] PROPERTIES WORKING_DIRECTORY /home/clem/Projects/krema/build_test_qt6_dir/tests/unit SKIP_RETURN_CODE 4)
add_test( [==[Smoke test]==] /home/clem/Projects/krema/build_test_qt6_dir/bin/krema_unit_tests [==[Smoke test]==]  )
set_tests_properties( [==[Smoke test]==] PROPERTIES WORKING_DIRECTORY /home/clem/Projects/krema/build_test_qt6_dir/tests/unit SKIP_RETURN_CODE 4)
add_test( [==[Dock input region computation]==] /home/clem/Projects/krema/build_test_qt6_dir/bin/krema_unit_tests [==[Dock input region computation]==]  )
set_tests_properties( [==[Dock input region computation]==] PROPERTIES WORKING_DIRECTORY /home/clem/Projects/krema/build_test_qt6_dir/tests/unit SKIP_RETURN_CODE 4)
add_test( [==[Surface geometry calculations]==] /home/clem/Projects/krema/build_test_qt6_dir/bin/krema_unit_tests [==[Surface geometry calculations]==]  )
set_tests_properties( [==[Surface geometry calculations]==] PROPERTIES WORKING_DIRECTORY /home/clem/Projects/krema/build_test_qt6_dir/tests/unit SKIP_RETURN_CODE 4)
add_test( [==[Dock screen rect computation]==] /home/clem/Projects/krema/build_test_qt6_dir/bin/krema_unit_tests [==[Dock screen rect computation]==]  )
set_tests_properties( [==[Dock screen rect computation]==] PROPERTIES WORKING_DIRECTORY /home/clem/Projects/krema/build_test_qt6_dir/tests/unit SKIP_RETURN_CODE 4)
set( krema_unit_tests_TESTS [==[Parabolic zoom factor]==] [==[Smoke test]==] [==[Dock input region computation]==] [==[Surface geometry calculations]==] [==[Dock screen rect computation]==])
